### ISSUE TITLE
[develop] Grains test failing in develop

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#1007]
The following test is failing in develop:

- integration.loader.test_ext_grains.LoaderGrainsTest.test_grains_overwrite

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/loader/test_ext_grains.py", line 52, in test_grains_overwrite
    self.assertEqual({'k2': 'v2'}, grains['a_custom'])
KeyError: u'a_custom'
```

https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py2/lastCompletedBuild/testReport/

@gtmanfred Can you fix this one?

**Comment by gtmanfred** [comment]
yeah, i can look

**Comment by rallytime** [comment]
I am no longer seeing this fail. Closing.
