### ISSUE TITLE
[develop] yumpkg unit test failure

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#1015]
There is a single unit test failing on the CentOS 7 builds (both py2 and py3).

- unit.modules.test_yumpkg.YumTestCase.test_yum_base_error

```
Traceback (most recent call last):
  File "/testing/tests/unit/modules/test_yumpkg.py", line 680, in test_yum_base_error
    yumpkg._get_yum_config()
  File "/usr/lib/python2.7/site-packages/_pytest/python_api.py", line 667, in __exit__
    fail(self.message)
  File "/usr/lib/python2.7/site-packages/_pytest/outcomes.py", line 96, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: DID NOT RAISE <class 'salt.exceptions.CommandExecutionError'>
```

https://jenkinsci.saltstack.com/job/develop/view/Python3/job/salt-centos-7-py3/lastCompletedBuild/testReport/

@gtmanfred Can you fix this up? This is one of the last tests failing regularly on CentOS tests in PRs, so I'd love to get those running green again. (The other one is #1000).

**Comment by gtmanfred** [comment]
We upgraded the centos ami on amazon to the newest version, since we are only seeing this error in PRs.

Waiting for verification to see if this fixes the issue for prs on old jenkins.

**Comment by rallytime** [comment]
I checked a couple of PRs this morning and this looks good now to me.
