### ISSUE TITLE
[2017.7] Debian 8 failing a service test

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#1022]
The following test is failing on Debian 8, Python 2, on the 2017.7 branch:

- integration.modules.test_service.ServiceModuleTest.test_service_disable_doesnot_exist

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/modules/test_service.py", line 135, in test_service_disable_doesnot_exist
    self.assertFalse(self.run_function('service.disable', [srv_name]))
AssertionError: True is not false
```

https://jenkinsci.saltstack.com/job/2017.7/job/salt-debian-8-py2/lastCompletedBuild/testReport/

**Comment by garethgreenaway** [comment]
@rallytime This seems to be working now.  Testing locally it ran find and the latest build it's also running without issue.

**Comment by rallytime** [comment]
@garethgreenaway Well, it wasn't failing before, but now this test is failing on the Debian 9 build.

Can you take another look?

https://jenkinsci.saltstack.com/job/2017.7/job/salt-debian-9-py2/lastCompletedBuild/testReport/

**Comment by rallytime** [comment]
@garethgreenaway Fantastic! Thank you!

**Comment by rallytime** [comment]
Ah, I hate to do this to you @garethgreenaway, but now this is failing on Debian 8 Py3. Can you take one more look?

https://jenkinsci.saltstack.com/job/2017.7.8/view/Python3/job/salt-debian-8-py3/lastCompletedBuild/testReport/

**Comment by garethgreenaway** [comment]
@rallytime Found the cause, the grains I was using for the conditional are different between py2 & py3.  Swapping it out for a different grain.

**Comment by rallytime** [comment]
Great! Thanks!
