### ISSUE TITLE
[2017.7] Arch failing a git integration test

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#1023]
The following test is failing on Arch, Python 2 and Python 3, on the 2017.7, 2018.3, and develop branches:

- integration.modules.test_git.GitModuleTest.test_worktree_add_rm
```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/modules/test_git.py", line 956, in test_worktree_add_rm
    self.assertTrue(worktree_add_prefix + worktree_path in ret)
AssertionError: False is not true
```

https://jenkinsci.saltstack.com/job/2017.7/job/salt-arch-py2/lastCompletedBuild/testReport/

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/48883.
