### ISSUE TITLE
[2017.7.8] test_compiler failure debian 8 py3

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1053]
The test `integration.states.test_compiler.CompileTest.test_jinja_deep_error` is failing on debian 8 py3:

```
Stacktrace

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_compiler.py", line 34, in test_jinja_deep_error
    ret[0].strip().endswith('Exception: hehehe'))
AssertionError: False is not true
```

https://jenkinsci.saltstack.com/job/2017.7.8/view/Python3/job/salt-debian-8-py3/lastFailedBuild/testReport/junit/integration.states.test_compiler/CompileTest/test_jinja_deep_error/

**Comment by rallytime** [comment]
Fixed with https://github.com/saltstack/salt/pull/49002 - this has been flaky on Debian 8 for a long time and difficult to reproduce.

**Comment by Ch3LL** [comment]
@rallytime this just failed here again? https://jenkinsci.saltstack.com/job/2017.7.8/view/Python3/job/salt-debian-8-py3/lastFailedBuild/

if you dont have time today i can look into it, as far as i know it should just be skipping the test.

**Comment by rallytime** [comment]
This is no longer failing. Closing.
