### ISSUE TITLE
[2017.7.8] py3 tornado tests are hanging

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1054]
The python3 tornado tests are hanging and dont finish a complete test run:

https://jenkinsci.saltstack.com/job/2017.7.8/view/Tornado/job/salt-ubuntu-1604-py3-tornado/

**Comment by rallytime** [comment]
Now that I think about it, isn't this expected @gtmanfred? We should probably disable those. We don't support Py3 + Tornado 5.

Thanks what this issue is tracking: https://github.com/saltstack/salt-jenkins/issues/995

**Comment by gtmanfred** [comment]
The py3 tests should be yes.

**Comment by gtmanfred** [comment]
We need to just disable all py3 tornado 5 tests until dmitry's fix is in.

**Comment by rallytime** [comment]
I disabled them all for now.

**Comment by gtmanfred** [comment]
We should open an issue on the devops repo to get @dubb-b or @KaiSforza to disable them in the build jobs until we get that fixed.
