### ISSUE TITLE
[2017.7.8] windows cmd tests failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1058]
The following tests are failing on windows python3: 

```
integration.modules.test_cmdmod.CMDModuleTest.test_script
integration.modules.test_cmdmod.CMDModuleTest.test_script_cwd
integration.modules.test_cmdmod.CMDModuleTest.test_script_cwd_with_space
```

https://jenkinsci.saltstack.com/job/2017.7.8/view/Python3/job/salt-windows-2016-py3/lastFailedBuild/#showFailuresLink

**Comment by rallytime** [comment]
Fixed with https://github.com/saltstack/salt/pull/49103
