### ISSUE TITLE
[2017.7.8] test_http_query failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1059]
On the transport tests `unit.templates.test_jinja.TestCustomExtensions.test_http_query` is failing

https://jenkinsci.saltstack.com/job/2017.7.8/view/Transport/job/salt-ubuntu-1604-py3-transport/4/

I also see it failing on debian 9 https://jenkinsci.saltstack.com/job/2017.7.8/view/Python3/job/salt-debian-9-py3/lastFailedBuild/

**Comment by rallytime** [comment]
This test is just a tad flaky since it depends on an external site. While the test is simple, it can fail randomly. Marking it as flaky.
