### ISSUE TITLE
[2017.7.8] Arch Py3 Not starting Test Deamons

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#1060]
https://jenkinsci.saltstack.com/job/2017.7.8/view/Python3/job/salt-arch-py3/lastFailedBuild/console

This is happening on 2017.7.8 ^

But I am sure it's happening on other branches as well.

@gtmanfred Can you look into this one?

**Comment by gtmanfred** [comment]
This is because archlinux's py3 is python3.7 which suffers from the async problem.

**Comment by rallytime** [comment]
You're right. Let's close this since we're tracking that effort elsewhere. I'll disable the 2017.7 tests.
