### ISSUE TITLE
[2018.3.3]unit.utils.test_event.TestAsyncEventPublisher.test_event_subscription failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1070]
On windows python 2 the test `unit.utils.test_event.TestAsyncEventPublisher.test_event_subscription` is failing

https://jenkinsci.saltstack.com/job/2018.3.3/job/salt-windows-2016-py2/lastFailedBuild/#showFailuresLink

**Comment by dwoz** [comment]
Resolved by: https://github.com/saltstack/salt/pull/49270
