### ISSUE TITLE
[2018.3.3] test_roots windows failures

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1071]
The tests

```
unit.fileserver.test_roots.RootsTest.test_file_hash
unit.fileserver.test_roots.RootsTest.test_serve_file
```

are failing on windows python2 

https://jenkinsci.saltstack.com/job/2018.3.3/job/salt-windows-2016-py2/lastFailedBuild/#showFailuresLink

**Comment by dwoz** [comment]
Fixed by: https://github.com/saltstack/salt/pull/49243
