### ISSUE TITLE
[2018.3.3] unit.fileserver.test_gitfs.GitfsConfigTestCase.test_per_saltenv_config failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1072]
The test `unit.fileserver.test_gitfs.GitfsConfigTestCase.test_per_saltenv_config` is failing on windows python2 

https://jenkinsci.saltstack.com/job/2018.3.3/job/salt-windows-2016-py2/lastFailedBuild/#showFailuresLink

**Comment by rallytime** [comment]
This isn't failing any more, so I will close this for now. Possibly flaky/resolved by some of the other fixes.
