### ISSUE TITLE
[2018.3.3] setUpClass (unit.fileserver.test_gitfs.GitPythonTest) failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1074]
The test `setUpClass (unit.fileserver.test_gitfs.GitPythonTest)` on windows is failing on python2

https://jenkinsci.saltstack.com/job/2018.3.3/job/salt-windows-2016-py2/lastFailedBuild/#showFailuresLink

**Comment by dwoz** [comment]
Resolved by https://github.com/saltstack/salt/pull/49244
