### ISSUE TITLE
[2018.3.3] arch python3 tests do not finish

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1075]
Currently the python3 arch tests are not finishing tests and timeout.

https://jenkinsci.saltstack.com/job/2018.3.3/view/Python3/job/salt-arch-py3/4/console

**Comment by Ch3LL** [comment]
ping @garethgreenaway any chance you can take a look here. 

i noticed all hte builds are timing out on this part:

```
test_exit_status_correct_usage (integration.shell.test_minion.MinionTest)
```

**Comment by Ch3LL** [comment]
any update on this @garethgreenaway

**Comment by garethgreenaway** [comment]
@Ch3LL Unfortunately I still haven't been able to find the cause.  It's definitely something in Python 3.7 and not specific to Arch though.

**Comment by Ch3LL** [comment]
unfortunately it looks like this is still hanging: https://jenkinsci.saltstack.com/job/2018.3.3/view/Python3/job/salt-arch-py3/15/console

not sure if you knew @garethgreenaway

**Comment by gtmanfred** [comment]
https://jenkinsci.saltstack.com/job/fluorine/view/Python3/job/salt-arch-py3/37/console

At least it is in unittests now.

**Comment by rallytime** [comment]
Oops, that closed automatically when it shouldn't have. :)

@garethgreenaway Can you make this your priority when you get back? @gtmanfred is currently on PTO, but there should be some more info in here from his work this week to get this moving again.

**Comment by rallytime** [comment]
Nice! These are no longer hanging, but we have a bunch of failures around the `errno` missing. Let's get those fixed up too.

**Comment by rallytime** [comment]
This is fixed now.
