### ISSUE TITLE
[windows] Integration host module test failing

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#1116]
The following test failed on a PR recently. I don't see it failing on the branch and it's not failing in the Linux tests, so perhaps it is flaky. @dwoz Can you look into this?

- `integration.modules.test_hosts.HostsModuleTest.test_add_host_formatting`

```
Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\integration\modules\test_hosts.py", line 185, in test_add_host_formatting
    self.run_function('hosts.add_host', ['192.168.1.1', 'host1'])
AssertionError: False is not true
```

Here's the link to the Jenkins failing, but I'm not sure how long it will be around: https://jenkinsci.saltstack.com/job/pr-windows2016-py2/job/PR-49500/1/

This failed on a merge-forward PR from 2017.7 to 2018.3, and it didn't have any changes relevant to that test: https://github.com/saltstack/salt/pull/49500

**Comment by dwoz** [comment]
Tackled in this PR https://github.com/saltstack/salt/pull/49679

**Comment by rallytime** [comment]
I just checked the branch and this is no longer failing.
