### ISSUE TITLE
[2018.3] Several pkg state tests failing on opensuse

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#1118]
The following tests started failing somewhat recently on the 2018.3 branch on opensuse:

- integration.states.test_pkg.PkgTest.test_pkg_cap_001_installed
- integration.states.test_pkg.PkgTest.test_pkg_cap_002_already_installed
- integration.states.test_pkg.PkgTest.test_pkg_cap_004_latest
- integration.states.test_pkg.PkgTest.test_pkg_cap_005_downloaded
- integration.states.test_pkg.PkgTest.test_pkg_cap_006_uptodate
- integration.states.test_pkg.PkgTest.test_pkg_cap_003_installed_multipkg_with_version

These tests were originally added about a year ago and they have probably been silently failing for a long time. After a git bisect, I tracked down the reason these started failing, and it was due to the change on [this line](https://github.com/saltstack/salt/pull/49372/files#diff-bf068eddc21be801b0b8e45a04ff15c9R211) in https://github.com/saltstack/salt/pull/49372/.

@garethgreenaway Can you take a look here? They shouldn't be too hard to track down as they fail reliably on opensuse.

**Comment by garethgreenaway** [comment]
Spent some time looking at this and traced it down to the first search call in the `resolve_capabilities` function, which logs an error because the search fails.  Looks like @mcalmer made this addition, so hopefully has some advice on how to handle properly handle it so that the test passes.

**Comment by mcalmer** [comment]
@garethgreenaway do you have the error message? Is there a zypper .log available or something like this?

**Comment by mcalmer** [comment]
@garethgreenaway on which opensuse version do you test?

**Comment by garethgreenaway** [comment]
@mcalmer 

Version:
```
kitchen@e7597a6ad01e:/tmp/kitchen/testing/salt/modules> cat /etc/SuSE-release 
openSUSE 42.3 (x86_64)
VERSION = 42.3
CODENAME = Malachite
```

This is the error that is logged via Salt 
```
kitchen@e7597a6ad01e:/tmp/kitchen/testing/salt/modules> sudo salt-call --local pkg.resolve_capabilities pkgs="['w3m_ssl']" refresh=False resolve_capabilities='True'
[ERROR   ] Command '[u'zypper', u'--non-interactive', u'--xmlout', u'--no-refresh', u'search', u'--match-exact', u'w3m_ssl']' failed with return code: 104
[ERROR   ] stdout: <?xml version='1.0'?>
<stream>
<message type="info">Loading repository data...</message>
<message type="info">Reading installed packages...</message>
<message type="info">No matching items found.</message>
</stream>
[ERROR   ] retcode: 104
local:
    - w3m
```
The Salt call is ultimately successful but produces an error when attempting the first search.

There is a zypper.log which has quite a lot of data in it:
https://www.dropbox.com/s/op322wjxm0wtlzg/zypper.log?dl=0

**Comment by mcalmer** [comment]
Return codes greater then 100 are not always errors. It just say "not found" which is ok.
I need to look deeper into it.
There was also https://github.com/saltstack/salt/pull/49722 fixed. It is a fix for python3.
But I think you still test with python2, right?

**Comment by garethgreenaway** [comment]
@mcalmer We are testing this on PY2 but the tests in question are failing on Py3 as well.  In the `search` function this particular line seems like it might be the issue.  https://github.com/saltstack/salt/blob/2018.3/salt/modules/zypper.py#L1989

**Comment by rallytime** [comment]
I have merged in the fix above, but there are some problems with the tests starting on opensuse, so I we can't confirm the results there until those are running again. We're tracking that work here: https://github.com/saltstack/release-mgmt/issues/432

**Comment by mcalmer** [comment]
```
$> ./tests/runtests.py --run-destructive --name=integration.states.test_pkg.PkgTest.test_pkg_cap_001_installed
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Python Version: 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
 * Transplanting configuration files to '/tmp/salt-tests-tmpdir/config'
 * Current Directory: /home/mc/CVS/SALT/salt
 * Test suite is running under PID 2851
 * Logging tests on /tmp/salt-runtests.log
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Max open files settings is too low (soft: 1024, hard: 4096) for running the tests
 * Trying to raise the limits to soft: 3072, hard: 4096
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Setting up Salt daemons to execute tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Starting salt-master ... STARTED!                                                                                                                                                         
 * Starting salt-minion ... STARTED!                                                                                                                                                         
 * Starting sub salt-minion ... STARTED!                                                                                                                                                     
 * Starting syndic salt-master ... STARTED!                                                                                                                                                  
 * Starting salt-syndic ... STARTED!                                                                                                                                                         
===============================
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting integration.states.test_pkg.PkgTest.test_pkg_cap_001_installed Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.
----------------------------------------------------------------------
Ran 1 test in 63.902s

OK

===  Overall Tests Report  ====
***  No Problems Found While Running Tests  **************************
===============================
OK (total=1, skipped=0, passed=1, failures=0, errors=0) 
===  Overall Tests Report  ====
$> cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="42.3"
...
```
The test is working on my workstation. So I cannot find out what's going wrong.
I think I need more info about the test setup. How can I reproduce the error?
