### ISSUE TITLE
[fluorine] Arch failing 2 pkg state tests

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#1127]
The following tests are failing on the `Fluorine` branch on Arch:

-  integration.states.test_pkg.PkgTest.test_pkg_001_installed
-  integration.states.test_pkg.PkgTest.test_pkg_002_installed_with_version

These are failing both on Py2 and Py3.

https://jenkinsci.saltstack.com/job/fluorine/job/salt-arch-py2/lastFailedBuild/
https://jenkinsci.saltstack.com/job/fluorine/view/Python3/job/salt-arch-py3/lastFailedBuild/

@terminalmage Can you look into these?

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/49799
