### ISSUE TITLE
Find a different way to test duplicate salt-call executions

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#1133]
The `test_local_pkg_install` was enabled recently in https://github.com/saltstack/salt/pull/49552

Unfortunately, this has caused some strangeness in the test suite and is causing the test suite to hang indefinitely. I have skipped the test in https://github.com/saltstack/salt/pull/49824 and https://github.com/saltstack/salt/pull/49825.

Since that test was enabled to catch a regression with duplicate `salt-call` executions, we need to either fix this test so the test suite doesn't hang. Or, alternatively, write a different test do catch the regression.

**Comment by terminalmage** [comment]
Should be fixed in https://github.com/saltstack/salt/pull/49854.

**Comment by rallytime** [comment]
Fixed.
