### ISSUE TITLE
[fluorine] integration.scheduler.test_eval tests failing on mac

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1134]
The `integration.scheduler.test_eval` tests are currently failing on mac. I do not currently have a link with each individual test failure since the jenkins re-build, but it can be replicated and I can share a mac VM for anyone to replicate it.

I did dive into the test `test_eval_days` which I found was failing because a previous schedule job was still running. If i added `time.sleep` between each call `self.schedule.job_status` call the tests would pass.

This is because when the schedule runs `_check_max_running` method it shows a previous job is still running so it will not run the currently schedule job and then fails.

ping @garethgreenaway any chance you can take a look into this?

**Comment by rallytime** [comment]
This looks fixed to me: 

https://jenkinsci.saltstack.com/job/fluorine/job/salt-mac-sierra-py2/lastCompletedBuild/testReport/
https://jenkinsci.saltstack.com/job/fluorine/view/Python3/job/salt-mac-sierra-py3/lastCompletedBuild/testReport/
