### ISSUE TITLE
[fluorine] Fix test failures on Cent7

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#1139]
There are 3 tests that are failing on CentOS7 that seem to be trouble-maker tests. I am not sure if they're all flaky or not, but they're all in that realm of tests.

@gtmanfred Can you track these down and fix them for fluorine?

- integration.runners.test_state.StateRunnerTest.test_orchestrate_subset
- integration.logging.test_jid_logging.LoggingJIDsTest.test_jid_in_logs
- integration.shell.test_matcher.MatchTest.test_salt_documentation_arguments_not_assumed

https://jenkinsci.saltstack.com/job/fluorine/job/salt-centos-7-py2/lastFailedBuild/

These are failing Python 2, and not Python 3. I also don't see these failures on 2018.3 presently. I have seen some of them on PRs as things are getting back going, but it would be good to get these cleaned up.

**Comment by gtmanfred** [comment]
opened saltstack/salt#50121 for this, marked the logging test as flaky, the other two are already marked as flaky.  Looking into them futher to see if i can make them better.

**Comment by gtmanfred** [comment]
I think this is working

**Comment by gtmanfred** [comment]
Verifying with https://jenkinsci.saltstack.com/job/fluorine/job/salt-centos-7-py2/24/

**Comment by gtmanfred** [comment]
The `integration.shell.test_matcher.MatchTest.test_salt_documentation_arguments_not_assumed` is still failing sometimes.

**Comment by rallytime** [comment]
That is a flaky test. I _think_ it should be resolved in the latest merge-forward (which just went in to fluorine about 2 minutes ago) because it contains this nice fix from @dwoz: https://github.com/saltstack/salt/pull/50212

**Comment by rallytime** [comment]
I'm going to call this one good for now. I can open a new issue if I see anything new pop up in the future.
