### ISSUE TITLE
[2018.3] mac_system integration tests are failing

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#1140]
The following tests are failing on Mac Sierra on the 2018.3 branch for both the py2 and py3 runs:

- integration.modules.test_mac_system.MacSystemModuleTest.test_get_list_startup_disk
- integration.modules.test_mac_system.MacSystemModuleTest.test_get_set_computer_name
- integration.modules.test_mac_system.MacSystemModuleTest.test_get_set_disable_keyboard_on_lock
- integration.modules.test_mac_system.MacSystemModuleTest.test_get_set_remote_events
- integration.modules.test_mac_system.MacSystemModuleTest.test_get_set_remote_login
- integration.modules.test_mac_system.MacSystemModuleTest.test_get_set_subnet_name

https://jenkinsci.saltstack.com/job/2018.3/view/Python3/job/salt-mac-sierra-py3/lastCompletedBuild/

https://jenkinsci.saltstack.com/job/2018.3/job/salt-mac-sierra-py2/lastFailedBuild/

@garethgreenaway Can you take a look at these and fix them up? 

I wouldn't be surprised if these are failing on fluorine as well, but we don't have any test data for that branch yet.

**Comment by garethgreenaway** [comment]
@rallytime There was a second line that needed to be updated.  That last PR takes care of it.

**Comment by rallytime** [comment]
@garethgreenaway This still isn't quite right. There are quite a few scheduler tests failing on the 2018.3 branch:

https://jenkinsci.saltstack.com/job/2018.3/job/salt-mac-sierra-py2/lastCompletedBuild/testReport/

**Comment by rallytime** [comment]
This looks good now. Thanks @garethgreenaway!
