### ISSUE TITLE
[fluorine] fedora 28 test_shadow tests failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1217]
The following tests on fluorine are failing on fedora 28: 

```
integration.modules.test_shadow.ShadowModuleTest.test_set_date
integration.modules.test_shadow.ShadowModuleTest.test_set_expire
```

https://jenkinsci.saltstack.com/job/fluorine/job/salt-fedora-28-py2/44/

**Comment by garethgreenaway** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1653260

**Comment by Ch3LL** [comment]
@garethgreenaway is there anything we can do to workaround this in the meantime? Or just wait until its fixed?

**Comment by garethgreenaway** [comment]
@Ch3LL No workarounds from what I can tell, there is an updated package with the fix that has been submitted not accepted into the repository yet.  But looks like it might be close: https://bodhi.fedoraproject.org/updates/FEDORA-2018-be8834ced4

**Comment by garethgreenaway** [comment]
There was an updated package that was supposed to fix the issue but I'm still seeing it.  Reported into the Red Hat bugzilla system.

**Comment by Ch3LL** [comment]
and are you certain we are installing that package on our test run?

**Comment by garethgreenaway** [comment]
The package is installed. It's not the latest version but manually installing it on kitchen salt created instance doesn't fix anything. It seems like perhaps it was fixed for a specific use case and didn't account for issues using chage.

**Comment by garethgreenaway** [comment]
It seems like https://github.com/saltstack/salt/pull/51079 allows these tests to pass.
