### ISSUE TITLE
[fluorine] mac highsierra unit.grains.test_core.CoreGrainsTestCase.test_xen_virtual

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1218]
the test `unit.grains.test_core.CoreGrainsTestCase.test_xen_virtual` is failing on mac high sierra and mac sierra.

https://jenkinsci.saltstack.com/job/fluorine/job/salt-mac-sierra-py2/61/
https://jenkinsci.saltstack.com/job/fluorine/job/salt-mac-highsierra-py2/67/

**Comment by dwoz** [comment]
Fixed in this PR https://github.com/saltstack/salt/pull/50716

**Comment by Ch3LL** [comment]
tests are passing
