### ISSUE TITLE
[fluorine] mac python3 pkg test failures

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1227]
integration.states.test_pkg.PkgTest.test_pkg_001_installed
integration.states.test_pkg.PkgTest.test_pkg_009_latest_with_epoch
integration.states.test_pkg.PkgTest.test_group_installed_handle_missing_package_group
integration.states.test_pkg.PkgTest.test_pkg_002_installed_with_version
integration.states.test_pkg.PkgTest.test_pkg_003_installed_multipkg
integration.states.test_pkg.PkgTest.test_pkg_004_installed_multipkg_with_version
integration.states.test_pkg.PkgTest.test_pkg_010_latest_with_epoch_and_info_installed
integration.states.test_pkg.PkgTest.test_pkg_011_latest
integration.states.test_pkg.PkgTest.test_pkg_015_installed_held

https://jenkinsci.saltstack.com/job/fluorine/view/Python3/job/salt-mac-sierra-py3/60/#showFailuresLink

**Comment by dwoz** [comment]
Looks like these are fixed on the latest sierra builds

https://jenkinsci.saltstack.com/job/fluorine/job/salt-mac-highsierra-py2/69/
and
https://jenkinsci.saltstack.com/job/fluorine/view/Python3/job/salt-mac-highsierra-py3/62/
