### ISSUE TITLE
[fluorine] mac virt tests

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1228]
integration.modules.test_virt.VirtTest.test_default_esxi_profile
integration.modules.test_virt.VirtTest.test_default_kvm_profile

https://jenkinsci.saltstack.com/job/fluorine/view/Python3/job/salt-mac-sierra-py3/60/#showFailuresLink

**Comment by garethgreenaway** [comment]
@Ch3LL Are there being actively skipped already?  Looking at the last test run, they're not in the failure list and in the console output they appear to have been skipped.

**Comment by Ch3LL** [comment]
Not that i'm aware of. They would need to have the skip added for mac. These tests are flaky and there is not a lot of value to run the test_virt tests on mac. this is approved via @thatch45

**Comment by thatch45** [comment]
Yes, in the future we will likely completely remove these and similar tests from Mac

**Comment by garethgreenaway** [comment]
Based on the last run it appears this are being skipped because dependancies aren't met:
```
22:19:22    -> integration.modules.test_virt.VirtTest.test_default_esxi_profile                                           ->  Salt module 'virt.get_profiles' is not available
22:19:22    -> integration.modules.test_virt.VirtTest.test_default_kvm_profile                                            ->  Salt module 'virt.get_profiles' is not available
```

```
14:59:36   test_default_esxi_profile (integration.modules.test_virt.VirtTest)
15:00:39 [CPU:50.0%|MEM:63.8%]  ... SKIP (63.475s)
15:00:39   test_default_kvm_profile (integration.modules.test_virt.VirtTest)
15:01:38 [CPU:0.0%|MEM:63.9%]  ... SKIP (60.070s)
```

**Comment by Ch3LL** [comment]
hmm odd and of course i can't check the URL that I initially saw the tests fail. Lets go ahead and close and if we see them again we can explicitly skip them on mac.
