### ISSUE TITLE
[fluorine] ec2 test cloud failures

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1230]
integration.cloud.clouds.test_ec2.EC2Test.test_win2012r2_psexec
integration.cloud.clouds.test_ec2.EC2Test.test_win2016_psexec

https://jenkinsci.saltstack.com/job/fluorine/view/Cloud/job/salt-centos-7-py2-cloud/39/

**Comment by dwoz** [comment]
These are passing finally.
