### ISSUE TITLE
[fluorine] vultr cloud python3 test failure

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1233]
integration.cloud.clouds.test_vultrpy.VultrTest.test_instance
https://jenkinsci.saltstack.com/job/fluorine/view/Cloud/job/salt-centos-7-py3-cloud/39/

**Comment by Ch3LL** [comment]
per @thatch45 's approval we are going to skip these tests going forward, for whoever is assigned this task.

**Comment by terminalmage** [comment]
So do you just want me to skip this, or actually troubleshoot it?

**Comment by Ch3LL** [comment]
just add the skipif(True) decorator

**Comment by terminalmage** [comment]
:+1: Thanks!

**Comment by terminalmage** [comment]
Done in https://github.com/saltstack/salt/pull/50836
