### ISSUE TITLE
[fluorine] beacon failures ubuntu 18 python3

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1239]
The test `integration.states.test_beacon.BeaconStateTestCase.test_present_absent` is failing on ubuntu 18 python3 

https://jenkinsci.saltstack.com/job/fluorine/view/Python3/job/salt-ubuntu-1804-py3/53/

**Comment by terminalmage** [comment]
Closing as a duplicate of https://github.com/saltstack/salt-jenkins/issues/1224 which is already assigned to me.

**Comment by Ch3LL** [comment]
thanks for catching that :)
