### ISSUE TITLE
[fluorine] windows 2016 unit git tests failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1244]
unit.fileserver.test_gitfs.GitPythonTest.test_disable_saltenv_mapping_global_with_mapping_defined_globally
unit.fileserver.test_gitfs.GitPythonTest.test_disable_saltenv_mapping_global_with_mapping_defined_per_remote
unit.fileserver.test_gitfs.GitPythonTest.test_disable_saltenv_mapping_per_remote_with_mapping_defined_globally
unit.fileserver.test_gitfs.GitPythonTest.test_disable_saltenv_mapping_per_remote_with_mapping_defined_per_remote
unit.fileserver.test_gitfs.GitPythonTest.test_envs
unit.fileserver.test_gitfs.GitPythonTest.test_file_list
unit.fileserver.test_gitfs.GitPythonTest.test_ref_types_global
unit.fileserver.test_gitfs.GitPythonTest.test_ref_types_per_remote

https://jenkinsci.saltstack.com/job/fluorine/job/salt-windows-2016-py2/56/

**Comment by dwoz** [comment]
Fixed by https://github.com/saltstack/salt/pull/50916
