### ISSUE TITLE
[fluorine] windows lgpo unit tests failing py3

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1246]
unit.utils.test_win_lgpo_netsh.WinLgpoNetshTestCase.test_set_firewall_settings_consecrules_local_enable
unit.utils.test_win_lgpo_netsh.WinLgpoNetshTestCase.test_set_firewall_settings_fwrules_local_enable

https://jenkinsci.saltstack.com/job/fluorine/view/Python3/job/salt-windows-2016-py3/55/

**Comment by twangboy** [comment]
This is passing locally on my test box. Waiting for the Branch tests to finish to see if this is still an issue.

https://jenkinsci.saltstack.com/job/2019.2.0.rc1/view/Python3/job/salt-windows-2016-py3/12/

**Comment by twangboy** [comment]
Did not see in latest 2019.2 test run
