### ISSUE TITLE
[2019.2.0rc1] windows tests timing out

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1252]
The tests on windows python3 are hanging and not completing the test run:

https://jenkinsci.saltstack.com/job/2019.2.0.rc1/view/Python3/job/salt-windows-2016-py3/8/console

ping @dwoz or @twangboy do you guys have any ideas here?

**Comment by Ch3LL** [comment]
thanks so are you looking into it @twangboy

**Comment by Ch3LL** [comment]
the tests pass when runtests is run outside of kitchen. We are going to skip these tests for fluorine so we can get test results and @twangboy will continue investigating.

**Comment by twangboy** [comment]
Until we can figure out what's going on ^^^

**Comment by Ch3LL** [comment]
i'm seeing this timeout again after a different spot

```
19:57:56          test_sync_all_blacklist (integration.modules.test_saltutil.SaltUtilSyncModuleTest)
20:42:56 Build timed out (after 45 minutes). Marking the build as aborted.
```

seems this is flaky behavior. Sometimes we get test results and sometimes its timing out.

**Comment by Ch3LL** [comment]
Issue moved to [saltstack/salt #51888](https://github.com/saltstack/salt/issues/51888) via [**ZenHub**](https://www.zenhub.com/)
