### ISSUE TITLE
[2018.3] integration.doc.test_man.ManTest.test_man failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1254]
the test `integration.doc.test_man.ManTest.test_man` is failing on python3 tests. here is an eample:

https://jenkinsci.saltstack.com/job/2018.3/view/Python3/job/salt-debian-8-py3/93/

**Comment by garethgreenaway** [comment]
https://github.com/saltstack/salt/pull/51209
