### ISSUE TITLE
[2018.3] cloud tests do not return test results

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1256]
The test results are not returning on both py3 adn py2 cloud tests on 2018.3

one thing that popped out to me was this:

```
16:29:32        chmod: cannot access ‘/var/log/salt/minion’: No such file or directory
16:29:32 >>>>>> ------Exception-------
16:29:32 >>>>>> Class: Kitchen::ActionFailed
16:29:32 >>>>>> Message: 1 actions failed.
16:29:32 >>>>>>     Failed to complete #verify action: [SSH exited (1) for command: [sudo -E chmod -R +r /var/log/salt/minion]] on py2-centos-7
16:29:32 >>>>>> ----------------------
```

ping @dubb-b any ideas here by chance?

**Comment by dubb-b** [comment]
Its here: https://github.com/saltstack/release-mgmt/blob/dev/states/services/jenkins-node/kitchen-install.sls#L509

Do we want to remove trying to grab these?

**Comment by Ch3LL** [comment]
shouldn't the logs be there?

**Comment by Ch3LL** [comment]
it looks like this is occuring on 2019.2.0rc1 py3 cloud tests as well

**Comment by dubb-b** [comment]
I will have to run a one and validate that the logs are not there.

**Comment by dubb-b** [comment]
@Ch3LL these are now fixed.
