### ISSUE TITLE
pylint failing but showing success

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1260]
Currently pylint on the following branches:
- 2017.7
- develop
- 2019.2
- 2019.2.0rc1
is failing but jenkins returns SUCCESS. 

ping @dubb-b is this something on your end or do i need a developer to dive in?

**Comment by Ch3LL** [comment]
heres an example: https://jenkinsci.saltstack.com/job/develop/view/Lint/job/salt-develop-lint/86/console

**Comment by dubb-b** [comment]
@Ch3LL these should all be correct now. I kicked each one off. They are returning correctly now it seems.
