### ISSUE TITLE
[2019.2.0] ssdp mac test failures

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1267]
the following tests are failing on mac 

unit.utils.test_ssdp.SSDPFactoryTestCase.test_datagram_signature_bad
unit.utils.test_ssdp.SSDPFactoryTestCase.test_datagram_signature_correct_timestamp_reply
unit.utils.test_ssdp.SSDPFactoryTestCase.test_datagram_signature_outdated_timestamp_quiet
unit.utils.test_ssdp.SSDPFactoryTestCase.test_datagram_signature_outdated_timestamp_reply
unit.utils.test_ssdp.SSDPFactoryTestCase.test_datagram_signature_wrong_timestamp_quiet
unit.utils.test_ssdp.SSDPFactoryTestCase.test_datagram_signature_wrong_timestamp_reply
unit.utils.test_ssdp.SSDPFactoryTestCase.test_transport_sendto_retry
unit.utils.test_ssdp.SSDPFactoryTestCase.test_transport_sendto_success

https://jenkinsci.saltstack.com/job/2019.2.0.rc1/job/salt-mac-highsierra-py2/20/

the last known good commit before the tests started failing was:

8850b37d45297471dcda5bf74a4d8104d1a33349

and first bad when tests started failing:

d6f4f055f567ecf44373bb15d13f575d40bedc25

**Comment by garethgreenaway** [comment]
Tests are passing in later builds so closing this out.
