### ISSUE TITLE
[2019.2.0] windows py2 not bootstrapping

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1268]
https://jenkinsci.saltstack.com/job/2019.2.0.rc1/job/salt-windows-2016-py2/17/consoleFull

```
17:18:43        [INFO    ] Executing command 'Powershell -NonInteractive -NoProfile "C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\testing\pkg\windows\build_env_2.ps1 -Silent"' in directory 'C:\Users\Administrator'
17:18:43        
17:25:54 >>>>>> ------Exception-------
17:25:54 >>>>>> Class: Kitchen::ActionFailed
17:25:54 >>>>>> Message: 1 actions failed.
17:25:54 >>>>>>     Failed to complete #converge action: [execution expired] on py2-windows-2016
17:25:54 >>>>>> ----------------------
```

and then it tries to converge the machine again and we see this error:

```
17:30:00        Transferring files to <py2-windows-2016>
17:31:29        local:
17:31:29            Data failed to compile:
17:31:29        ----------
17:31:29            The function "state.highstate" is running as PID 3264 and was started at 2019, Jan 25 22:18:42.218000 with jid 20190125221842218000
```

**Comment by Ch3LL** [comment]
ping @dubb-b can you take a look here?

**Comment by dubb-b** [comment]
@Ch3LL working on this today

**Comment by dubb-b** [comment]
@Ch3LL https://jenkinsci.saltstack.com/job/2019.2.0.rc1/job/salt-windows-2016-py2/20/console

There was an intermit issue with the file transfer. I changed the AWS instance type to a better and faster model. The systems seem to bootstrap much faster now. I have not seen the timeout in the last two builds. There are test failures to fix though still.
