### ISSUE TITLE
[2017.7] fedora 29 py3 not running tests

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1274]
on 2017.7 fedora 29 python 3 we are seeing this error when trying to start the test runner:

```
12:00:58        Running Command: python3 /tmp/kitchen/testing/tests/runtests.py --sysinfo --output-columns=80  --transport=zeromq -v --run-destructive --coverage-xml=/tmp/coverage.xml --xml=/tmp/xml-unittests-output/ --ssh   2>&1
12:00:59        Traceback (most recent call last):
12:00:59          File "/tmp/kitchen/testing/tests/runtests.py", line 61, in <module>
12:00:59            from tests.integration import TestDaemon  # pylint: disable=W0403
12:00:59          File "/tmp/kitchen/testing/tests/integration/__init__.py", line 37, in <module>
12:00:59            from tests.support.case import ShellTestCase
12:00:59          File "/tmp/kitchen/testing/tests/support/case.py", line 144
12:00:59            def run_run(self, arg_str, with_retcode=False, catch_stderr=False, async=False, timeout=60, config_dir=None):
12:00:59                                                                            ^
12:00:59        SyntaxError: invalid syntax
12:00:59        chmod: cannot access '/tmp/xml-unittests-output': No such file or directory
```

https://jenkinsci.saltstack.com/job/2017.7/view/Python3/job/salt-fedora-29-py3/23/console

**Comment by waynew** [comment]
I'm having a heck of a time reproducing this locally... Are there other tests running on this same box? I could see a race condition happening here, if that's the case. But otherwise... seems to be running fine on a vagrant box?

**Comment by waynew** [comment]
Hm, not sure if it has anything to do with the problem, but earlier in the logs it does show this:
```
10:54:02        Error: Error downloading packages:
10:54:02          Cannot download Packages/l/libsolv-0.7.2-1.fc29.x86_64.rpm: All mirrors were tried
10:54:02         * ERROR: Failed to run install_fedora_git_deps()!!!
10:54:02        No salt-minion installed, install must have failed!!
10:54:02        salt_install = bootstrap
``` (I don't *think* that would cause a problem!)

**Comment by waynew** [comment]
Oh hey! I finally did! well, sort of! After like... my entire test suite ran, I got:

`No such file or directory /tmp/salt-tests-tempdir/config/sshd.pid`. Now to see if I can repro with a more simple sample 😛

**Comment by waynew** [comment]
Hah! Perfect - running on `-n unit` gets me that failure, reliably

**Comment by waynew** [comment]
Okay, finally, even better, I'm actually reproducing this exact error!

**Comment by waynew** [comment]
Just needed to install bundle/ruby a la https://github.com/saltstack/kitchen-salt/blob/master/docs/gettingstarted.md and then running 

    cd /path/to/salt
    bundle install
    bundle exec kitchen converge py3-fedora
    bundle exec kitchen verify py3-fedora

 I *did* adjust the `.kitchen.yml` file to specify that fedora should be `fedora:29` vs `fedora:latest`. But I'm getting the same error and now I can figure out exactly what's happening here.

**Comment by waynew** [comment]
🤦‍♂️ `async=False`

**Comment by waynew** [comment]
Yeah, I'm hoping there's a single commit in the modern branch(es) that we can backport that does all of the `async` -> `asynchronous` renames that we can backport. Looks like it's just a matter of fedora 29 using a modern version of Python 😀

**Comment by waynew** [comment]
Okay, so I found the PR/branch: https://github.com/saltstack/salt/pull/48705/commits

I know I can cherry-pick that list... might just be what I have to do, since it's only those changes that I want.

**Comment by waynew** [comment]
I think we've got the tests *running* now 👍
