### ISSUE TITLE
macOS Failures: Due to saltstack.net artifactory deprecation

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/salt-jenkins#1726]
MacOS build failures are occurring due to the deprecation of the `saltstack.net` artifactory:

```
15:03:47  ERROR: Could not find credentials entry with ID 'artifactory-apikey'
15:03:48  [GitHub Checks] GitHub check (name: ci/macosx-catalina-x86_64, status: COMPLETED) has been published.
15:04:16  Finished: FAILURE
```

Job refs:
- https://jenkins.saltproject.io/job/Full-PR/job/full-pr-macosx-catalina-x86_64/job/PR-1714/39/console
- https://jenkins.saltproject.io/job/Full-PR/job/full-pr-macosx-mojave-x86_64/job/PR-1714/39/console

The macOS builds need to be revisited, and updated to use a new pathway.

**Comment by s0undt3ch** [comment]
The new MacOS golden images will be redone from scratch and will not rely on artifactory.
