### ISSUE TITLE
Fedora 33 and 34 docker container builds: Kitchen test failures with SSH

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/salt-jenkins#1729]
SSH fails to work properly when test-kitchen tries bringing up Fedora containers.

Fedora 33 example:
 - https://jenkins.saltproject.io/job/Full-PR/job/full-pr-fedora-33-x86_64-docker/job/PR-1714/40/console

Fedora 34 example:
- https://jenkins.saltproject.io/job/Full-PR/job/full-pr-fedora-34-x86_64-docker/job/PR-1714/40/console

```
...
...
...
16:14:07         Waiting for SSH service on localhost:49154, retrying in 3 seconds
16:14:10         Waiting for SSH service on localhost:49154, retrying in 3 seconds
16:14:13  $$$$$$ [SSH] connection failed, terminating (#<Net::SSH::AuthenticationFailed: Authentication failed for user kitchen@localhost>)
16:14:13  >>>>>> ------Exception-------
16:14:13  >>>>>> Class: Kitchen::ActionFailed
16:14:13  >>>>>> Message: 1 actions failed.
16:14:13  >>>>>>     Failed to complete #create action: [SSH session could not be established] on py3-fedora-33-x86-64
16:14:13  >>>>>> ----------------------
16:14:13  >>>>>> Please see .kitchen/logs/kitchen.log for more details
16:14:13  >>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by bryceml** [comment]
this is probably because they both don't support rsa with sha1 anymore. It's a similar problem for the AMI.  We use user_data on the ami to add it back.  It will only be so long until they stop supporting it in openssh at all.

**Comment by krionbsd** [comment]
This one is fixed with new keys
