### ISSUE TITLE
Busybox.net has frequent timeouts

### ISSUE THREAD

**Issue by s0undt3ch** [saltstack/salt-jenkins#1748]
In this issue is the **exact same binary** with the exception that it has a file extension of `.zip`, but it's in fact, the real **uncompressed** binary since we couldn't upload the binary without a GitHub supported file extension.

[busybox.zip](https://github.com/saltstack/salt-jenkins/files/8031454/busybox.zip)

The sha256sum of the file we uploaded.
```
d270442b2fff1c8ebbd076afaf2f6739abc5790526acfafd8fcdba3eab80ed73  busybox.zip
```

We'll pull the binary from the link in this issue until busybox.net stops timing out so much.

**Comment by krionbsd** [comment]
@s0undt3ch I guess this one is fixed? Can you confirm?

**Comment by s0undt3ch** [comment]
The new golden images will not include BusyBox.
