### ISSUE TITLE
[develop] Arch is failing git_pillar integration tests

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#314]
There are 32 tests currently failing on the Arch build in the develop branch:
https://jenkins.saltstack.com/job/branch_tests/job/develop/

They are all tests in the `integration.pillar.test_git_pillar` file.

The arch tests haven't been running recently because of some bootstrapping issues, so I am not sure where these started failing.

@terminalmage Perhaps you might now what is happening there, since I believe you were working on these tests most recently.

**Comment by terminalmage** [comment]
The salt-runtests.log shows that all of the HTTP tests are failing with 404 errors when trying to fetch. This is likely a bit of weirdness with how nginx is being setup on that platform.

**Comment by terminalmage** [comment]
Fixed by https://github.com/saltstack/salt/pull/41050.
