### ISSUE TITLE
Fix UBUNTU16 Bootstrap Issue on Ubuntu16 Image in OpenNebula

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#320]
@Ch3LL commented on [Thu Apr 27 2017](https://github.com/saltstack/zh/issues/1274)

Currently I am running into this issue: https://github.com/saltstack/salt-bootstrap/issues/1023 when trying to bootstrap off of the ubuntu16 image in opennebula. Need to troubleshoot why the service is getting masked. And possibly add ability to bootstrap to unmask if it is masked. This is preventing cloud tests from running on ubuntu16, currently they are running on ubuntu14

**Comment by rallytime** [comment]
@Ch3LL Just checking in here. Is this still an issue?

**Comment by Ch3LL** [comment]
yes i just checked and its still not bootstrapping

**Comment by Ch3LL** [comment]
no longer using opennebula. closing
