### ISSUE TITLE
[2016.11] Arch integration.shell.matcher test is failing

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#324]
The following test is failing on Arch on the [2016.11](https://jenkins.saltstack.com/job/branch_tests/job/2016.9/) branch:
- integration.shell.matcher.MatchTest.test_salt_documentation_arguments_not_assumed

This appears to be a bug in salt-testing. The version of salt testing that is installed is gated to version 2016.9.7 [here](https://github.com/saltstack/salt-jenkins/blob/2016.11/python/salttesting.sls#L9). When you run the test off of the develop version of salt-testing, the failure goes away. 

The error is quite strange as @terminalmage points out that the place the test is failing should be caught, but it isn't. Here's the test failure:
```
Traceback (most recent call last):
  File "/testing/tests/integration/shell/matcher.py", line 315, in test_salt_documentation_arguments_not_assumed
    data = self.run_salt('-d -t 20')
  File "/testing/tests/integration/__init__.py", line 1878, in run_salt
    return self.run_script('salt', arg_str, with_retcode=with_retcode, catch_stderr=catch_stderr, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/salttesting/case.py", line 325, in run_script
    out = tmp_file.read().decode(__salt_system_encoding__)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 34683: ordinal not in range(128)
```
But the code in salt-testing looks like this:
```
try:
    out = tmp_file.read().decode(__salt_system_encoding__)
except (NameError, UnicodeDecodeError):
    # Let's cross our fingers and hope for the best
    out = tmp_file.read().decode('utf-8')
```
So the error _should_ be caught.

We might just need to update the version of salt-testing, but that might have adverse effects on other distributions. Or allow the test to fail for the time being.

@cachedout what do you think about spending time on this test?

Thanks to @terminalmage for tracking this down.

**Comment by cachedout** [comment]
Just disable it for Arch. It's not platform-specific anyway and if the matcher fails, we'll know it.

**Comment by rallytime** [comment]
Sounds good! Thanks @cachedout!

**Comment by rallytime** [comment]
Fixed by https://github.com/saltstack/salt/pull/41074
