### ISSUE TITLE
[2017.5] Python 3 Tests are not running all tests

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#333]
The Python 3 tests on both the `2017.5` and `develop` branches are not running all tests. This is likely due to a memory leak of some kind. The tests are currently running on 8G instances on Linode, but they are still only running a little less than 1,000 tests out of the nearly 7,000 tests that should be running.

This issue is to track the work that needs to be done on getting the Python 3 tests running the entire test suite. @s0undt3ch Might have more information on this, but I am not sure.

FYI @cachedout

**Comment by cachedout** [comment]
Assigned to @DmitryKuzmenko already via email.

**Comment by rallytime** [comment]
This has been fixed. 🎉  

Well done @DmitryKuzmenko!
