### ISSUE TITLE
[2017.5] CentOS 7 failing integration.renderers.test_pydsl test on Python 3

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#334]
The `integration.renderers.test_pydsl.PyDSLRendererIncludeTestCase.test_rendering_includes` is failing on the [2017.5 Python 3](https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/) tests for CentOS 7:
```
Traceback (most recent call last):
  File "/testing/tests/integration/renderers/test_pydsl.py", line 50, in test_rendering_includes
    with salt.utils.fopen('/tmp/output', 'r') as f:
  File "/testing/salt/utils/__init__.py", line 1345, in fopen
    fhandle = open(*args, **kwargs)  # pylint: disable=resource-leakage
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/output'
```

**Comment by terminalmage** [comment]
Another that I can't reproduce. I also can't find an example of this one failing in the recent results for this job (Build History area [here](https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/job/salt-linode-py3-cent7/)), so I have no access to logs that might tell me more.

**Comment by rallytime** [comment]
Ok, I checked the most recent runs across all distros and I can't find an instance of this failing again. Maybe some of your recent PRs cleaned this up. We can open this again if needed.
