### ISSUE TITLE
2017.5] CentOS 7 failing integration.loader.test_ext_modules test on Python 3 

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#336]
The `integration.loader.test_ext_modules.LoaderOverridesTest.test_overridden_internal` is failing on the [2017.5 Python 3](https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/) tests for CentOS 7:
```
Traceback (most recent call last):
  File "/testing/tests/integration/loader/test_ext_modules.py", line 42, in test_overridden_internal
    self.assertIn('test.ping', funcs)
  File "/usr/lib64/python3.4/unittest/case.py", line 1094, in assertIn
    if member not in container:
TypeError: argument of type 'bool' is not iterable
```
Likely related to #335

**Comment by garethgreenaway** [comment]
Running the test individually and I cannot reproduce it.

**Comment by rallytime** [comment]
I don't see this failing anywhere lately on CentOS 7 builds, or any other distro. I'll close this and we can open it again if we see it pop up.
