### ISSUE TITLE
[2017.5] Several distros failing integration.states.test_file test on Python 3

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#339]
The `integration.states.test_file.FileTest.test_issue_11003_immutable_lazy_proxy_sum` is failing on the [2017.5 Python 3](https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/) tests for several distros:
```
Lists differ: ['#',[29 chars]SE, DO NOT EDIT', 'bar', '', 'baz', '#-- end managed zone', ''] != ['#',[29 chars]SE, DO NOT EDIT', 'baz', '', 'bar', '#-- end managed zone', '']  First differing element 2: bar baz    ['#',    '#-- start managed zone PLEASE, DO NOT EDIT', +  'baz', +  '',    'bar', -  '', -  'baz',    '#-- end managed zone',    '']
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/integration/states/test_file.py", line 2042, in test_issue_11003_immutable_lazy_proxy_sum
    contents
AssertionError: Lists differ: ['#',[29 chars]SE, DO NOT EDIT', 'bar', '', 'baz', '#-- end managed zone', ''] != ['#',[29 chars]SE, DO NOT EDIT', 'baz', '', 'bar', '#-- end managed zone', '']

First differing element 2:
bar
baz

  ['#',
   '#-- start managed zone PLEASE, DO NOT EDIT',
+  'baz',
+  '',
   'bar',
-  '',
-  'baz',
   '#-- end managed zone',
   '']
```

This test is failing on the following distros:
- CentOS 7
- Debian 8
- SUSE LEAP

**Comment by terminalmage** [comment]
I can't get this to fail on nitrogen, but I can on develop. @rallytime, please ping me after the next time you complete a merge-forward from nitrogen to develop, it's possible that this was already fixed.

**Comment by rallytime** [comment]
@terminalmage I _just_ merged one in here about an hour ago: https://github.com/saltstack/salt/pull/41466

**Comment by terminalmage** [comment]
I've found the issue here. The states in this test use file.accumulated, which accumlate data in a msgpack-serialized dict, which the file.blockreplace state iterates over to include the accumulated data between the block markers. The failures come down to the hashing being different in different Python versions, resulting in different iteration order, which the state does not account for (likely because it was only written with Python 2 in mind).

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/41471.
