### ISSUE TITLE
[2017.5] Several distros failing integration.modules.test_cmdmod test on Python 3

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#340]
The `integration.modules.test_cmdmod.CMDModuleTest.test_run` is failing on the [2017.5 Python 3](https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/) tests for several distros:
```
Traceback (most recent call last):
  File "/testing/tests/integration/modules/test_cmdmod.py", line 51, in test_run
    python_shell=True).rstrip(), shell)
AssertionError: '/bin/bash' != '/bin/sh'
- /bin/bash
?      --
+ /bin/sh
```

This test is failing on the following distros:
- CentOS 7
- Debian 8
- SUSE LEAP
- Ubuntu 16.04

**Comment by terminalmage** [comment]
Can't reproduce. The test looks really straightforward, too, it's just getting the shell from os.environ and then making sure that echoing $SHELL is the same.

Perhaps something elsewhere in the suite is causing it to fail by modifying os.environ.

**Comment by terminalmage** [comment]
I've opened https://github.com/saltstack/salt/pull/41308 as a potential fix. This looks to be the culprit since it sets the SHELL to ``/bin/sh``. So, if it is run before the failing test, it would appear to be responsible for ``os.environ['SHELL'`` being different from ``$SHELL``.
