### ISSUE TITLE
[2017.5] A test_all_jobs from the rest_cherrypy tests is failing on Python 3

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#348]
The `integration.netapi.rest_cherrypy.test_app.TestJobs.test_all_jobs` test is failing in the [2017.5 Python 3](https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/) tests with the following error:
```
Traceback (most recent call last):
  File "/testing/tests/integration/netapi/rest_cherrypy/test_app.py", line 256, in test_all_jobs
    resp = json.loads(response.body[0])
  File "/usr/lib64/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by terminalmage** [comment]
Fixed locally, PR forthcoming with other test fixes included.

**Comment by terminalmage** [comment]
Fixed by https://github.com/saltstack/salt/pull/41293.
