### ISSUE TITLE
[2017.5] A couple of virt module integration tests are failing

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#349]
The `integration.modules.test_virt` test file has about 2 tests failing on the [2017.5 Python 3](https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/) tests. 

- [ ] `integration.modules.test_virt.VirtTest.test_default_esxi_profile`
```
Traceback (most recent call last):
  File "/testing/tests/integration/modules/test_virt.py", line 38, in test_default_esxi_profile
    nicp = profiles['nic']['default']
TypeError: 'bool' object is not subscriptable
```
- [ ] `integration.modules.test_virt.VirtTest.test_default_kvm_profile`
```
Traceback (most recent call last):
  File "/testing/tests/integration/modules/test_virt.py", line 25, in test_default_kvm_profile
    nicp = profiles['nic']['default']
TypeError: 'bool' object is not subscriptable
```

**Comment by terminalmage** [comment]
@rallytime Where is this failing? I can't find these in any of the jobs listed in the link provided. Also, I can't get this to fail on a Cent7 VirtualBox VM.

**Comment by rallytime** [comment]
@terminalmage Hrm....I saw this one fail on a CentOS 7 build yesterday. This link is here:

https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/job/salt-linode-py3-cent7/56/

**Comment by terminalmage** [comment]
Yeah, but I still can't reproduce this, and what's more, there doesn't appear to be any way in which the function being called under-the-hood to gather the profile data could possible result in a boolean value.

**Comment by terminalmage** [comment]
Like #349, I can't reproduce this and the item which is apparently supposed to be a bool (i.e. the return from ``grain.items`` can't possibly be a bool.

I feel like something elsewhere in the suite might have gone wrong, causing functions elsewhere to be mocked, or something. I honestly have no good explanation.

**Comment by rallytime** [comment]
@terminalmage When you run these, do the tests actually run on Python 3? Now the builds are showing that these tests are being skipped when I looked to see if these tests were a problem still today. So that is curious.

We can probably close this for now since I don't see any recent builds failing this test. We can come back to it if necessary.
