### ISSUE TITLE
[develop] 3 integration tests for zookeeper are failing in Python 3

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#354]
These tests are new to the `develop` branch of salt, but they are failing on the [Python 3 tab](https://jenkins.saltstack.com/job/branch_tests/job/develop/view/Python%203/) on the develop branch tests.

The tests that are failing are:
- integration.states.test_zookeeper.ZookeeperTestCase.test_zookeeper_present 
- integration.states.test_zookeeper.ZookeeperTestCase.test_zookeeper_absent
- integration.states.test_zookeeper.ZookeeperTestCase.test_zookeeper_acls

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/41468
