### ISSUE TITLE
Intermittent Test failures on Windows 2017.5 Py2 tests

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt-jenkins#373]
Random tests fail intermittently
https://jenkins.saltstack.com/job/branch_tests/job/2017.5/job/salt-dev-c7-windows-py2/

Here are some runs and the tests that failed:
https://docs.google.com/a/saltstack.com/spreadsheets/d/1DjMfwF9KBJbg5-wV3k30T48rYM2beUGwe8ZVVx7J8LE/edit?usp=sharing

Also a link to the ZH issue that summarizes the above spreadsheet:
https://github.com/saltstack/zh/issues/1272#issuecomment-302479288

**Comment by rallytime** [comment]
@twangboy Should this issue remain open, or is this covered by the new issues you filed yesterday to track test fixes?

**Comment by twangboy** [comment]
I don't know. I haven't look for intermittent failures in a while. There are a few tests that fail in Jenkins, but pass when run manually, so I'll have to hunt those down and see what's going on.
