### ISSUE TITLE
Add proxy auto tests to jenkins

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#374]
Auto Proxy Tests were written and need to be added to Jenkins. Since there was a flag added here https://github.com/saltstack/salt/pull/41113/files#diff-bf0d7f89b37ba018fb5c5b2833b37dd3R362 `--proxy` we will have to create new jenkins jobs because it will not run alongside the default tests.

Steps include:

1. Add a new Jenkins job for Branches: 2016.11, nitrogen
2. Add a job per branch for the following Operating Systems: Cent7, Ubuntu16

Thanks for @rallytime bringing this to my attention :+1: 

@dubb-b any chance you can tackle this one? should be pretty quick. If not I can tackle it when i get away from mac tests.

**Comment by rallytime** [comment]
I should note here that `2016.11` should work with @cro's proxy minion test additions, but I wasn't able to merge those changes forward to `nitrogen` or `develop` because of the large refactors to the test suite. I commented about that [here](https://github.com/saltstack/salt/pull/41113#issuecomment-303460715) on @cro's pull request.

**Comment by cro** [comment]
Thanks Nicole.  I will take an AI to fix these for Nitrogen.

*--cro*
C. R. Oldham
Senior Platform Engineer, SaltStack
cr@saltstack.com / 801-564-4673

**Comment by dubb-b** [comment]
@Ch3LL Ill work on this...

**Comment by dubb-b** [comment]
I added jobs for 2016.11 @cro can you validate that they are ok?
https://jenkins.saltstack.com/job/branch_tests/job/Proxy/

The Cent7 one failed, I think it looked right. But not 100% sure.

**Comment by cro** [comment]
I'm not sure they are being run.  When I look through the tests I don't see
any 'integration.proxy.*'.  There are some unit tests, but they were not
part of my PR and didn't need the proxy daemons running.  I setup
runtests.py to require --proxy (or -P/-p, can't remember the case) to
execute the proxy integration tests.


*--cro*
C. R. Oldham
Senior Platform Engineer, SaltStack
cr@saltstack.com / 801-564-4673

**Comment by dubb-b** [comment]
@Ch3LL 
I have the 2016.11 Jobs setup and working for CentOS7 and Ubuntu 16. The 2017.5/Nitrogen are not complete. I will finish them when @cro fixes it for Nitrogen.

**Comment by rallytime** [comment]
https://github.com/saltstack/salt/pull/41617 adds this to nitrogen. It hasn't been merged yet, but just wanted to make sure you knew it was there @dubb-b

**Comment by dubb-b** [comment]
@rallytime do we need the jenkins jobs created now?

**Comment by rallytime** [comment]
@dubb-b Looks like that fix was merged, so yeah.

**Comment by dubb-b** [comment]
2017.7 Proxy tests added and are passing

**Comment by rallytime** [comment]
@dubb-b Did you add develop ones as well?

**Comment by dubb-b** [comment]
Nope, I will do it now.

**Comment by dubb-b** [comment]
@rallytime develop is now added

**Comment by rallytime** [comment]
Awesome - Thank you!
