### ISSUE TITLE
Unit tests to not run on Windows when using the `--names-file` switch

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt-jenkins#375]
The `--names-file` switch is intended to pass a text file with the names of the tests to run. It only works with integration tests. Unit tests don't run if you pass the `--names-file` switch. I also tried adding unit tests to the `whitelist.txt`, but they cause an error. Perhaps we need to run the tests twice, once with the whitelist, and again running unit tests.

**Comment by rallytime** [comment]
This is being tracked elsewhere. Closing.
