### ISSUE TITLE
Python3 Fix Test: `integration.cloud.providers.test_digital_ocean.DigitalOceanTest.test_instance`

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#395]
Currently the salt-cloud test `integration.cloud.providers.test_digital_ocean.DigitalOceanTest.test_instance` is failing on python3 with the following failure: 

```
10:02:48    -> integration.cloud.providers.test_digital_ocean.DigitalOceanTest.test_instance  
10:02:48        Traceback (most recent call last):
10:02:48          File "/testing/tests/integration/cloud/providers/test_digital_ocean.py", line 159, in test_instance
10:02:48            [i.strip() for i in self.run_cloud('-p digitalocean-test {0}'.format(INSTANCE_NAME), timeout=500)]
10:02:48        AssertionError: 'CLOUD-TEST-YN0LKA' not found in []
```

**Comment by rallytime** [comment]
@Ch3LL This should be fixed by https://github.com/saltstack/salt/pull/41558, but let's see how the cloud tests go in case I missed something. Please let me know how the test run goes after that PR is merged.

**Comment by Ch3LL** [comment]
This is passing now
