### ISSUE TITLE
Python3: Fix Test: AzureTest.test_instance

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#397]
Currently the test `integration.cloud.providers.test_msazure.AzureTest.test_instance` is failing on python3 salt-cloud tests on the head of nitrogen with the error:

```
10:02:48    -> integration.cloud.providers.test_msazure.AzureTest.test_instance  ........
10:02:48        Traceback (most recent call last):
10:02:48          File "/testing/tests/integration/cloud/providers/test_msazure.py", line 139, in test_instance
10:02:48            ), timeout=TIMEOUT
10:02:48        AssertionError: 'CLOUD-TEST-Q9E3DA' not found in []
```

**Comment by rallytime** [comment]
@Ch3LL This should be fixed by https://github.com/saltstack/salt/pull/41558, but let's see how the cloud tests go in case I missed something. Please let me know how the test run goes after that PR is merged.

**Comment by Ch3LL** [comment]
This is passing now! woot woot
