### ISSUE TITLE
Python 3 Fix test: RackspaceTest.test_instance

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#399]
Currently the test `integration.cloud.providers.test_rackspace.RackspaceTest.test_instance` is failing on python3 salt-cloud tests on the head of nitrogen with error:

```
10:02:48    -> integration.cloud.providers.test_rackspace.RackspaceTest.test_instance  ..
10:02:48        Traceback (most recent call last):
10:02:48          File "/testing/tests/integration/cloud/providers/test_rackspace.py", line 96, in test_instance
10:02:48            [i.strip() for i in self.run_cloud('-p rackspace-test {0}'.format(INSTANCE_NAME), timeout=500)]
10:02:48        AssertionError: 'CLOUD-TEST-3AGUOP' not found in []
```

**Comment by rallytime** [comment]
@Ch3LL This should be fixed by https://github.com/saltstack/salt/pull/41558, but let's see how the cloud tests go in case I missed something. Please let me know how the test run goes after that PR is merged.

**Comment by Ch3LL** [comment]
This is passing now :)
