### ISSUE TITLE
Python 3: Fix test: VMWareTest.test_instance

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#400]
Currently the test `integration.cloud.providers.test_vmware.VMWareTest.test_instance` is failing on python3 salt-cloud tests on the head of nitrogen with the error:

```
10:02:48    -> integration.cloud.providers.test_vmware.VMWareTest.test_snapshot  ........
10:02:48        Traceback (most recent call last):
10:02:48          File "/testing/tests/integration/cloud/providers/test_vmware.py", line 132, in test_snapshot
10:02:48            self.assertIn(s_ret_str, str(create_snapshot))
10:02:48        AssertionError: 'Snapshot created successfully' not found in "['Not Actioned/Not Running:', '    - CLOUD-TEST-BJL0GN', 'Not Found:', '    - CLOUD-TEST-BJL0GN']"
```

**Comment by rallytime** [comment]
@Ch3LL This should be fixed by https://github.com/saltstack/salt/pull/41558, but let's see how the cloud tests go in case I missed something. Please let me know how the test run goes after that PR is merged.

**Comment by Ch3LL** [comment]
This is passing now
