### ISSUE TITLE
Python 3 Fix test: VultrTest.test_instance

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#401]
Currently the test `integration.cloud.providers.test_vultr.VultrTest.test_instance` is failing on python3 salt-cloud tests on the head of nitrogen with the error:

```
10:02:48    -> integration.cloud.providers.test_vultr.VultrTest.test_instance  ..........
10:02:48        Traceback (most recent call last):
10:02:48          File "/testing/tests/integration/cloud/providers/test_vultr.py", line 163, in test_instance
10:02:48            [i.strip() for i in create_vm]
10:02:48        AssertionError: 'CLOUD-TEST-O8568M' not found in []
```

**Comment by rallytime** [comment]
@Ch3LL This should be fixed by https://github.com/saltstack/salt/pull/41558, but let's see how the cloud tests go in case I missed something. Please let me know how the test run goes after that PR is merged.

**Comment by Ch3LL** [comment]
I'm still seeing the same error:

```
10:32:40    -> integration.cloud.providers.test_vultr.VultrTest.test_instance  ..........
10:32:40        Traceback (most recent call last):
10:32:40          File "/testing/tests/integration/cloud/providers/test_vultr.py", line 163, in test_instance
10:32:40            [i.strip() for i in create_vm]
10:32:40        AssertionError: 'CLOUD-TEST-VP7763' not found in []
```

**Comment by rallytime** [comment]
Ah, I set up the vultr cloud driver and got this to fail in PY3. This PR fixes the issue nicely and should fix the tests as well: https://github.com/saltstack/salt/pull/41600

@Ch3LL Let me know if this still needs more work after the next test run.

**Comment by rallytime** [comment]
I checked the last test run results and it looks like this is fixed.
