### ISSUE TITLE
[Python 3 MacOSX] Fix integration.cli.test_grains.SSHGrainsTest.test_grains_id 

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#409]
Error Message

> {'_error': 'Failed to return clean data',[1209 chars]: 10} != 'localhost'
Stacktrace

> Traceback (most recent call last):
  File "/testing/tests/integration/cli/test_grains.py", line 89, in test_grains_id
    self.assertEqual(cmd, 'localhost')
AssertionError: {'_error': 'Failed to return clean data',[1209 chars]: 10} != 'localhost'

**Comment by gtmanfred** [comment]
Closing, This was solved by putting python3 in the default path for sh on the mac testing boxes
