### ISSUE TITLE
[Python 3 MacOSX] Fix multiple test_pip tests

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#410]
The flowing tests are failing with the same error:

integration.modules.test_pip.PipModuleTest.test_pip_install_multiple_editables 
integration.modules.test_pip.PipModuleTest.test_pip_install_multiple_editables_and_pkgs

Error Message

>1 != 0

Stacktrace

>Traceback (most recent call last):
  File "/testing/tests/integration/modules/test_pip.py", line 424, in test_pip_install_multiple_editables_and_pkgs
    self.assertEqual(ret['retcode'], 0)
AssertionError: 1 != 0

**Comment by gtmanfred** [comment]
Pip tests did not fail in the latest py3 run.

http://mac-jenkins.lehi.saltstack.net:8080/job/2017.5/job/macOS-py3-10.12/23/#showFailuresLink
