### ISSUE TITLE
[Python 3 MacOSX] Fix integration.cli.test_custom_module.SSHCustomModuleTest tests

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#412]
The following ssh tests are failing with the same error:
integration.cli.test_custom_module.SSHCustomModuleTest.test_ssh_regular_module
integration.cli.test_custom_module.SSHCustomModuleTest.test_ssh_custom_module
integration.cli.test_custom_module.SSHCustomModuleTest.test_ssh_sls_with_custom_module

Error Message

>'olleh' != {'stdout': 'ERROR: salt requires python 2[1253 chars]: 10}

Stacktrace

>Traceback (most recent call last):
  File "/testing/tests/integration/cli/test_custom_module.py", line 63, in test_ssh_custom_module
    self.assertEqual(expected, cmd)
AssertionError: 'olleh' != {'stdout': 'ERROR: salt requires python 2[1253 chars]: 10}

**Comment by gtmanfred** [comment]
Closing, This was solved by putting python3 in the default path for sh on the mac testing boxes
