### ISSUE TITLE
[2016.11.6] Fix unit.transport.tcp_test.AESReqTestCases.test_badload

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#428]
Currently on the head of 2016.11 the test `unit.transport.tcp_test.AESReqTestCases.test_badload` is failing with the error:

```
Error Message

DummyFuture does not support blocking for results
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/unit/transport/tcp_test.py", line 135, in test_badload
    ret = self.channel.send(msg)
  File "/testing/salt/utils/async.py", line 75, in wrap
    ret = self._block_future(ret)
  File "/testing/salt/utils/async.py", line 85, in _block_future
    return future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 216, in result
    self._check_done()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 294, in _check_done
    raise Exception("DummyFuture does not support blocking for results")
Exception: DummyFuture does not support blocking for results

Stderr:
Exception RuntimeError: RuntimeError('IOLoop is already running',) in <bound method AsyncTCPReqChannel.__del__ of <salt.transport.tcp.AsyncTCPReqChannel object at 0x7fee67efb150>> ignored
```

**Comment by rallytime** [comment]
This is one test that I consider flaky. I think it should still be investigated, but this one has been failing off and on for some time now on all testing branches.

**Comment by Ch3LL** [comment]
Oh okay I was having a hard time replicating this. I think i replicated it once out of 10 test runs

I did notice that the tests started failing consistently on debian8 on jenkins after this commit: aab55d304abf622685bacf97a415fcffa07fa862 which is this https://github.com/saltstack/salt/pull/41696 

But i was only able to reproduce once out of 10 so i will not consider this a 2016.11 blocker then

**Comment by rallytime** [comment]
Oh interesting...I didn't know there was somewhere that it was failing consistently. I definitely see this fail occasionally across all distros and on each branch. But if something is causing it to fail more frequently, we should look into it. I agree with you that it shouldn't be a blocker though.

**Comment by Ch3LL** [comment]
Yeah its failing consistantly on jenkins but not when i run it locally. It only replicated once so it might still be flaky but coincidence to fail 4-5 times ina row on debian8

**Comment by Ch3LL** [comment]
@terminalmage we think this is a flaky test but do you see any obvious relationship between your PR and the test failure?
