### ISSUE TITLE
Add Debian 9 to Auto Tests in Jenkins

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#441]
Need to add Debian 9 for 2016.3/2016.11/2017.7/develop for the branch jenkins jobs at https://jenkins.saltstack.com/job/branch_tests/

ping @dubb-b think you can grab this?

**Comment by rallytime** [comment]
@Ch3LL we'll probably need to do another release of the bootstrap script with support for Debian 9 as well before this will working in jenkins.

**Comment by Ch3LL** [comment]
Good point. Thanks for pointing that out.

**Comment by rallytime** [comment]
@Ch3LL and @dubb-b I added official Debian 9 support to salt-bootstrap, merged in this morning to the `develop` branch of salt-bootstrap. https://github.com/saltstack/salt-bootstrap/pull/1111

We'll probably want to do a release sometime soon. Fedora 26 is coming out soon as well. I am not sure if we want to wait for that or not.

**Comment by dubb-b** [comment]
@rallytime py2 & py3 right?

**Comment by dubb-b** [comment]
@rallytime This has been setup in Jenkins. Most of all the py2 jobs have been tested and the py3 jobs fail on some tests.

I have a few queued, I will check them after.

**Comment by rallytime** [comment]
I think we can close this issue now. Any other problems that surface on the Debian 9 tests we can make individual issues for. Thanks @dubb-b!
