### ISSUE TITLE
Add a python3 pylint linter

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#473]
This issue is to track the addition of a python3 pylint linter for pull request tests. @rallytime this has been assigned to you but please feel free to use the resources of @dubb-b when you are ready to add the pylinter to jenkins.

**Comment by rallytime** [comment]
@Ch3LL Can you explain more what is needed to add? The linter already checks for _many_ Python 3 issues. So if there is something you're looking for that is more specific that should be added to the existing linter, that would be helpful.

**Comment by rallytime** [comment]
@Ch3LL I never heard back on this. Can you elaborate on what this request is about?

**Comment by Ch3LL** [comment]
TBH I can't quit remember what this was exactly for. I will go ahead and close and we can re-open if needed.
