### ISSUE TITLE
[2016.11] Fedora 26 failing pkg integration test

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#474]
- integration.modules.pkg.PkgModuleTest.test_hold_unhold

https://jenkins.saltstack.com/job/branch_tests/job/2016.9/job/salt-2016_9-linode-fedora26/lastCompletedBuild/testReport/integration.modules.pkg/PkgModuleTest/test_hold_unhold/

**Comment by terminalmage** [comment]
This was fixed in https://github.com/saltstack/salt/pull/42651, but that PR was opened against `2017.7` I've backported it to `2016.11` in https://github.com/saltstack/salt/pull/42851.

**Comment by rallytime** [comment]
Fedora 26 on 2016.11 is blue!
