### ISSUE TITLE
Arch is failing npm cache test

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#475]
-  integration.states.npm.NpmStateTest.test_npm_cache_clean

https://jenkins.saltstack.com/job/branch_tests/job/2016.9/job/salt-2016_9-linode-arch/lastCompletedBuild/testReport/integration.states.npm/NpmStateTest/test_npm_cache_clean/

This test is failing on all relevant branches, so it should be fixed in 2016.11.

**Comment by gtmanfred** [comment]
This is expected.

https://github.com/saltstack/salt/issues/41770

**Comment by rallytime** [comment]
@gtmanfred So what are we doing here with jenkins then? Can we add some logic to the test to not run with incompatible versions?

**Comment by gtmanfred** [comment]
Ahh, yes sorry, i missed that the label was for 2016.11.8 and .7.2, we should gate it for those releases.

**Comment by rallytime** [comment]
@gtmanfred That would be great! Thank you :)

**Comment by gtmanfred** [comment]
Fixed in saltstack/salt#42856
