### ISSUE TITLE
[2017.7] PY3 Debian 8 has several vmware unit tests failing

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#480]
The test report is [here](https://jenkins.saltstack.com/job/branch_tests/job/2017.7/view/Python%203/job/salt-linode-py3-debian8/lastCompletedBuild/testReport/), but there are many tests failing there. The test failures for this issue are the following:

unit.utils.vmware_test.test_connection.PrivateGetServiceInstanceTestCase.test_second_attempt_successful_connection 
unit.utils.vmware_test.test_connection.PrivateGetServiceInstanceTestCase.test_second_attempt_unsuccsessful_connection_default_error
unit.utils.vmware_test.test_connection.PrivateGetServiceInstanceTestCase.test_second_attempt_unsuccsessful_connection_vim_fault
unit.utils.vmware_test.test_connection.PrivateGetServiceInstanceTestCase.test_third_attempt_successful_connection
unit.utils.vmware_test.test_connection.PrivateGetServiceInstanceTestCase.test_third_attempt_unsuccessful_connection_detault_error
unit.utils.vmware_test.test_connection.PrivateGetServiceInstanceTestCase.test_third_attempt_unsuccessful_connection_vim_fault

Which are all located in the `unit.utils.vmware_test` file...which now that I think about it, is not named correctly. **Test files should start with `test_*` in the 2017.7 branch.** I thought we had a lint check for this, but perhaps it is missing this file somehow.

**Comment by gtmanfred** [comment]
I think this is being caused by this change

https://www.python.org/dev/peps/pep-0476/#id31

**Comment by rallytime** [comment]
These are passing now 🎉

**Comment by gtmanfred** [comment]
![*beep beep* dats da sound of da police.... *beep beep*](https://i.imgur.com/V3vk51H.gif)
