### ISSUE TITLE
[2017.7] PY3 minion black out tests

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#481]
There are two tests failing on 2017.7 for Python 3:

- integration.minion.test_blackout.MinionBlackoutTestCase.test_blackout_nonwhitelist
- integration.minion.test_blackout.MinionBlackoutTestCase.test_blackout

Here is the [arch build](https://jenkins.saltstack.com/job/branch_tests/job/2017.7/view/Python%203/job/salt-lin-py3-arch/lastCompletedBuild/testReport/) and the [fedora 26 build](https://jenkins.saltstack.com/job/branch_tests/job/2017.7/view/Python%203/job/salt-linode-py3-fedora26/lastCompletedBuild/testReport/) that have the test failures. (Along with many others.)

These are failing on both the Arch builds and the Fedora 26 builds. I know @gtmanfred spent some time on these previously, but wasn't able to find the problem. I also attempted to reproduce these failures briefly a couple of weeks ago, but did not have time to dive too deeply. This seems more like a test problem than a code problem, but still something we should get fixed if possible.

Perhaps @terminalmage will have some better luck. @terminalmage I am assigning this to you to see if you can reproduce them and see what the issue is after you get finished with the other salt-jenkins assigned to you.

**Comment by terminalmage** [comment]
I can't reproduce this. I tried locally using a docker container into which I installed Python 3 and the Py3 depchain, and I also tested on a Linode box using Brett's Jenkins tool. In neither case was I able to reproduce.

**Comment by rallytime** [comment]
Since the tests pass on their own, I don't think this should block any releases. I'll remove the version label. 

Thanks @terminalmage!

**Comment by terminalmage** [comment]
On Friday I built another box using our Jenkins dev box tool, which successfully bootstrapped and ran the salt-jenkins SLS. I tried a full run of the test suite and was not able to reproduce the failures.

**Comment by terminalmage** [comment]
As @gtmanfred noted, this may have to do with Python 3.6 as only Fedora 26 and Arch seem to be exhibiting these failures. I will try with a Fedora 26 box.

**Comment by Ch3LL** [comment]
any progress on this issue?

**Comment by terminalmage** [comment]
@Ch3LL I haven't done any further investigation with this, as I was never able to reproduce despite spending several hours and using two VMs and a container to try to reproduce.

**Comment by rallytime** [comment]
These are no longer failing. Closing.
