### ISSUE TITLE
fedora 26 python3 is failing salt-jenkins states

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#497]
Currently fedora 26 on python3 2017.7 branch is failing during the salt-jenkins states step `pytest-catchlog`

https://jenkins.saltstack.com/job/branch_tests/job/2017.7/view/Python%203/job/salt-linode-py3-fedora26/62/console

ping @dubb-b can you look at this.

**Comment by dubb-b** [comment]
@Ch3LL I fixed the salt-jenkins states, the tests are failing now with 3 errors.
https://jenkins.saltstack.com/job/branch_tests/job/2017.7/view/Python%203/job/salt-linode-py3-fedora26/lastCompletedBuild/testReport/

Let me know if you need anything else. I don't think my changes are related to the tests errors, but I will let you decide.

**Comment by Ch3LL** [comment]
yep looks good thanks!
