### ISSUE TITLE
Cent6 2016.11.8 Tests are not bootstrapping

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#503]
The cent6 2016.11.8 tests are failing during the attempt to bootstrap the minion. Here is the link:

https://jenkins.saltstack.com/job/branch_tests/job/2016.11.8/job/salt-2016_11_8-linode-cent6/

ping @dubb-b mind taking a look at this?

**Comment by dubb-b** [comment]
@Ch3LL 
I found the issue with the new slave and fixed it.

There was some code added to the 2016_9 Slave that was custom to that slave. I have added it to the 2016.11.8 slave and its running now.

After you validate can you close this?

**Comment by Ch3LL** [comment]
Looks good! Tests are running! thanks
