### ISSUE TITLE
[2017.7.2] Boto Tests Failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#508]
The following boto tests are failing on all OSs:

unit.modules.test_boto_vpc.BotoVpcSubnetsTestCase.test_that_when_a_subnet_does_not_exist_the_subnet_exists_method_returns_false

unit.modules.test_boto_vpc.BotoVpcTestCase.test_that_when_checking_if_a_vpc_exists_by_id_and_a_vpc_does_not_exist_the_vpc_exists_method_returns_false

unit.modules.test_boto_vpc.BotoVpcTestCase.test_that_when_describing_vpc_by_id_it_returns_the_dict_of_properties_returns_false

https://jenkins.saltstack.com/job/branch_tests/job/2017.7.2/job/2017.7.2_salt-linode-debian8/8/

Here is the traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/moto/core/models.py", line 70, in wrapper
    result = func(*args, **kwargs)
  File "/testing/tests/unit/modules/test_boto_vpc.py", line 296, in test_that_when_checking_if_a_vpc_exists_by_id_and_a_vpc_does_not_exist_the_vpc_exists_method_returns_false
    self.assertFalse(vpc_exists_result['exists'])
KeyError: 'exists'
```

This seems to be failing on all branches too. I tested it on 2017.7.1 and its also failing so my initial guess is its related to a boto or moto upgraded version in salt-jenkins. 

ping @gtmanfred mind taking a look here? Need to determine if this needs to get fixed for 2017.7.2 or if its just a test failure and clean it up. Thanks

**Comment by Ch3LL** [comment]
actually going to assign this to @rallytime since she has been fixing some aspects of these boto tests.

**Comment by rallytime** [comment]
This should be fixed by https://github.com/saltstack/salt/pull/43648

Closing for now. I'll re-open if needed.
