### ISSUE TITLE
Fedora 26 and Arch SPM test failure

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#545]
The following test is failing on Fedora 26 and Arch: `integration.spm.test_build.SPMBuildTest.test_spm_build_big_file`. This is failing both in PY2 and PY3.

It's odd that it is failing even though https://github.com/saltstack/salt/pull/44364 has already been merged.

This is on the 2017.7, oxygen, and develop branches. Arch is only failing in Oxygen - maybe something to do with the Amazon AMIs.

@Ch3LL I think this will need another look for Fedora 26.

**Comment by rallytime** [comment]
This same test is also failing on Fedora 25. I have updated the title to reflect this.

**Comment by Ch3LL** [comment]
Fixed by #45112
