### ISSUE TITLE
[develop] Salt utils path is printing warnings about deprecated paths

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#547]
I have only seen this happen when running `boto`-related unit tests, but I can't be 100% sure that is the problem. I am seeing the following warnings being printed over and over again in the console output for test runs:
```
21:59:51   test_absent_when_resource_does_not_exist (unit.states.test_boto_vpc.BotoVpcInternetGatewayTestCase)
21:59:51 [CPU:50.5%|MEM:29.3%] /testing/salt/utils/__init__.py:1734: DeprecationWarning: Use of 'salt.utils.namespaced_function' detected. This function has been moved to 'salt.utils.functools.namespaced_function' as of Salt Oxygen. This warning will be removed in Salt Neon.
22:00:23 /testing/salt/utils/__init__.py:521: DeprecationWarning: Use of 'salt.utils.which' detected. This function has been moved to 'salt.utils.path.which' as of Salt Oxygen. This warning will be removed in Salt Neon.
```
The tricky thing here is that I can't find any references that are using the old paths ANYWHERE for either the `namespaced_function` or `which` functions.

I am wondering if the boto tests are doing something tricky to trigger this, or if there is something else that I am missing.

**Comment by terminalmage** [comment]
The correct path for the offending function call is in the test results for https://github.com/saltstack/salt/pull/44442 thanks to changes I made to the stacklevel in the `salt/utils/__init__.py` convenience functions. I've fixed the deprecated call in the wordpress execution module in https://github.com/saltstack/salt/pull/44442/commits/d4e00f30f125f9391d51bc7e32a328df13e2f9af.

Closing.

**Comment by rallytime** [comment]
Thanks @terminalmage!
