### ISSUE TITLE
[develop] Test unit.serializers.test_serializers.TestSerializers.test_serialize_yaml failling on Cent6

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#557]
The test `unit.serializers.test_serializers.TestSerializers.test_serialize_yaml ` is failing on Cent6 on develop

Here is the error:

```
Traceback (most recent call last):
  File "/testing/tests/unit/serializers/test_serializers.py", line 51, in test_serialize_yaml
    assert serialized == '{encrypted_data: !encrypted foo, foo: bar}', serialized
AssertionError: {encrypted_data: !encrypted 'foo', foo: bar}
```

https://jenkins.saltstack.com/job/branch_tests/job/develop/job/salt-linode-cent6/3442/testReport/junit/unit.serializers.test_serializers/TestSerializers/test_serialize_yaml/

**Comment by rallytime** [comment]
This has been fixed.
