### ISSUE TITLE
[develop] centos7 python3 tests aren't bootstrapping

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#561]
https://jenkins.saltstack.com/job/branch_tests/job/develop/view/Python%203/job/salt-linode-py3-cent7/1817/console

`[ERROR   ] Profile rs_cent7_8192 is not defined`

Should be a pretty easy fix to set it the the appropriate profile.

ping @dubb-b mind taking a look here?

**Comment by dubb-b** [comment]
@Ch3LL I will fix this one. i might have been the cause.

**Comment by dubb-b** [comment]
@Ch3LL @rallytime @gtmanfred Is there a reason this is not being ran in Linode like the rest? This is configured for Rackspace.

**Comment by gtmanfred** [comment]
not as far as I know.

**Comment by rallytime** [comment]
Not that i know of. It's running in rackspace, even though the profile says linode?

**Comment by dubb-b** [comment]
@rallytime I switched it over and ran it. Tests are running now. Ill validate that the rest are on linode.

**Comment by dubb-b** [comment]
Looks to be all good now. Let me know if you want anything changed.

**Comment by rallytime** [comment]
thanks brett!
