### ISSUE TITLE
Add Fedora 27 to Branch Tests

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#562]
We need to add fedora 27 to our branch tests. 

ping @dubb-b looks like linode does not have an image available, any other ideas. Maybe adding to nebula instance depending on the status of things there?

cc @rallytime

**Comment by rallytime** [comment]
Linode is usually pretty quick to get new images up, so I am surprised they don't have one yet. I'll check again tomorrow or next week.

**Comment by dubb-b** [comment]
We have Fedora27 tests running in ON, I wouldn't rely on those yet. As soon as an image comes available I can add it.

**Comment by dubb-b** [comment]
I checked today, nothing yet.

**Comment by dubb-b** [comment]
Nothing yet...

**Comment by Ch3LL** [comment]
any update yet? Is there possibly another cloud provider we could use?

**Comment by dubb-b** [comment]
Fedora is added, can you validate and close? @Ch3LL

**Comment by gtmanfred** [comment]
Confirmed
