### ISSUE TITLE
[Python 3] failing integration.modules.test_state.StateModuleTest.test_exclude

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#583]
The following test is failing on Ubuntu 16 Python 3 builds on PRs:
- integration.modules.test_state.StateModuleTest.test_exclude

@garethgreenaway I have assigned this to you to look at when you get a chance. This must have snuck in when the Python 3 tests were down earlier this week.

I have seen it on many PR tests, so it should be easy to reproduce. :)

**Comment by garethgreenaway** [comment]
@rallytime Not seeing any recent PRs where this test is failing.

**Comment by rallytime** [comment]
@garethgreenaway Hrm. It's failing on the branch right now: https://jenkins.saltstack.com/job/Oxygen/view/Branch%20Python%203/job/oxygen-salt-ubuntu16.04-py3/lastCompletedBuild/testReport/junit/integration.modules.test_state/StateModuleTest/test_exclude/

There are many Py3 test failures currently, so it might be getting buried in the list. Are you able to reproduce it?

**Comment by rallytime** [comment]
@garethgreenaway Actually, that build was from a couple of days ago and I don't see it failing on the latest build: https://jenkins.saltstack.com/job/Oxygen/view/Branch%20Python%203/job/oxygen-salt-ubuntu16.04-py3/16/#showFailuresLink

I'll close this. If it pops up again I will reopen. :)

**Comment by rallytime** [comment]
This popped up again, but was fixed by https://github.com/saltstack/salt/pull/45158
