### ISSUE TITLE
test_pillar_refresh sometimes fails

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#584]
I have seen this fail occasionally on PRs. In this case, it was a CentOS7 run:
-integration.modules.test_saltutil.SaltUtilSyncPillarTest.test_pillar_refresh

```
Traceback (most recent call last):
  File "/testing/tests/integration/modules/test_saltutil.py", line 192, in test_pillar_refresh
    self.assertIn(pillar_key, post_pillar.get(pillar_key, 'didnotwork'))
AssertionError: 'itworked' not found in 'didnotwork'
```

@Ch3LL Was this one of the new tests you wrote?

**Comment by Ch3LL** [comment]
Yes i'll assign it to myself. The timeout might need to be increased even more.
