### ISSUE TITLE
[oxygen] CentOS 7 is failing several boto tests with module import failures

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#603]
- unittest.loader.ModuleImportFailure.unit.modules.test_boto_elb
- unittest.loader.ModuleImportFailure.unit.modules.test_boto_secgroup
- unittest.loader.ModuleImportFailure.unit.modules.test_boto_vpc
- unittest.loader.ModuleImportFailure.unit.modules.test_boto_route53
- unittest.loader.ModuleImportFailure.unit.states.test_boto_vpc
- unittest.loader.ModuleImportFailure.unit.utils.test_boto

**Comment by terminalmage** [comment]
I dug into the boto source code this morning and it is apparently trying to load data from a file called `endpoints.json`. In my testing docker image this file _does_ have a `partitions` key. I'm spinning up a dev box using Brett's tool here: https://jenkins.saltstack.com/view/All/job/dev_env_builder/78/console

**Comment by terminalmage** [comment]
I was able to import `boto.ec2` on the dev box I spawned above. ¯\_(ツ)_/¯

**Comment by gtmanfred** [comment]
It is worth mentioning that we are not seeing this error at all when running with kitchen-salt.

Also, even if these fail to load, the test still runs, which is super weird too.
