### ISSUE TITLE
[oxygen] CentOS 7 is failing one test in  integration.cli.test_grains

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#605]
- integration.cli.test_grains.SSHGrainsTest.test_grains_id

**Comment by Ch3LL** [comment]
Its passing now: https://jenkins.saltstack.com/job/Oxygen/job/oxygen-salt-cent7-py2/39/testReport/integration.cli.test_grains/SSHGrainsTest/test_grains_id/
