### ISSUE TITLE
[oxygen] Ubuntu 16 PY3 Failing 6 tests in integration.states.test_docker_container

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#608]
- integration.states.test_docker_container.DockerContainerTestCase.test_run_force
- integration.states.test_docker_container.DockerContainerTestCase.test_run_replace
- integration.states.test_docker_container.DockerContainerTestCase.test_run_with_creates
- integration.states.test_docker_container.DockerContainerTestCase.test_run_with_onlyif
- integration.states.test_docker_container.DockerContainerTestCase.test_run_with_unless

@terminalmage Can you look into this?

**Comment by terminalmage** [comment]
These are fixed locally and will be added to the PY3 fixes I've been appending to https://github.com/saltstack/salt/pull/45038.
