### ISSUE TITLE
[oxygen] MacOSX py3 test_download_a failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#646]
The test integration.modules.test_mac_softwareupdate.MacSoftwareUpdateModuleTest.test_download_all is failing with error:

```
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/support/helpers.py", line 88, in wrap
    return caller(cls)
  File "/testing/tests/integration/modules/test_mac_softwareupdate.py", line 159, in test_download_all
    self.run_function('softwareupdate.download_all'), list)
AssertionError: "ERROR executing 'softwareupdate.download_all': Update not available: Mac App Store Update for OS X El Capitan- " is not an instance of <class 'list'>
```

http://mac-jenkins:8080/job/oxygen/job/macOS-py3-10.11/3/testReport/junit/integration.modules.test_mac_softwareupdate/MacSoftwareUpdateModuleTest/test_download_all/

**Comment by frogunder** [comment]
I could not replicate this,  will re-run the tests to see if it was just flaky behavior

**Comment by frogunder** [comment]
This test did not fail  when I re-run the tests.

```
Passed

integration.modules.test_mac_softwareupdate.MacSoftwareUpdateModuleTest.test_download_all (from integration.modules.test_mac_softwareupdate.MacSoftwareUpdateModuleTest-20180104161021)
```

http://mac-jenkins.lehi.saltstack.net:8080/job/oxygen/job/macOS-py3-10.11/6/testReport/integration.modules.test_mac_softwareupdate/MacSoftwareUpdateModuleTest/test_download_all/

**Comment by rallytime** [comment]
@Ch3LL This OK to close?

**Comment by Ch3LL** [comment]
Yep! thanks @frogunder :)
