### ISSUE TITLE
[oxygen] MacOSX 10.11 Py 3 test_append_newline_at_eof failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#648]
The test unit.modules.test_file.FileModuleTestCase.test_append_newline_at_eof is failing on MacOSX 10.11 py3 with error:

```
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/unit/modules/test_file.py", line 594, in test_append_newline_at_eof
    'bar' + os.linesep
AssertionError: "b'bar'\n" != 'bar\n'
- b'bar'
+ bar
```

http://mac-jenkins:8080/job/oxygen/job/macOS-py3-10.11/3/testReport/junit/unit.modules.test_file/FileModuleTestCase/test_append_newline_at_eof/

**Comment by rallytime** [comment]
@Ch3LL Is this failing recently? This was failing in linux at the time as well but has since been fixed with https://github.com/saltstack/salt/pull/45463

**Comment by rallytime** [comment]
I am pretty sure this was fixed because it was failing in linux too. I'm going to close this. We can re-open if it pops back up.
