### ISSUE TITLE
[2016.11] Ubuntu 14 failing in git.salt state run

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#673]
```
21:32:05 ----------
21:32:05           ID: deb_locale
21:32:05     Function: service.running
21:32:05         Name: dbus.socket
21:32:05       Result: False
21:32:05      Comment: The named service dbus.socket is not available
21:32:05      Started: 21:27:25.302180
21:32:05     Duration: 27.911 ms
21:32:05      Changes:  
```

This is likely due to the change in #597, which was back-ported to 2016.11 in #661.

@gtmanfred I am wondering if when you marked that for back-port, you intended for that only to go to the 2017.7 branch? Should I just revert that backport for 2016.11? (And make sure that the original PR is is 2017.7?)

**Comment by gtmanfred** [comment]
Yeah, it should have only gone back to 2017.7, that is my bad.

There was this pr that makes it so the dbus stuff is only run on systemd systems, but it was merged into 2017.7 https://github.com/saltstack/salt-jenkins/pull/525

We only really need this block of stuff for test suites that we are running on amazon.

**Comment by rallytime** [comment]
Ok, I'll just back port that PR so we can get those bootstrapping again. That will probably be easiest. Then we won't have to catch those if we decide switch 2016.11 to amazon.

**Comment by rallytime** [comment]
This is fixed!
