### ISSUE TITLE
[2017.7] New test_man_spm test is failing on Debian 9

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#674]
@frogunder Since you wrote this new test, can you look into this?

```
Traceback (most recent call last):
  File "/testing/tests/integration/spm/test_man_spm.py", line 21, in test_man_spm
    self.assertIn('Salt Package Manager', cmd)
AssertionError: 'Salt Package Manager' not found in 'No manual entry for spm'
```

https://jenkins.saltstack.com/job/2017.7/job/salt-2017_7-linode-debian9/lastCompletedBuild/testReport/integration.spm.test_man_spm/SPMManTest/test_man_spm/
  
It looks like this is failing on CentOS 6 as well: https://jenkins.saltstack.com/job/2017.7/job/salt-linode-cent6/lastCompletedBuild/testReport/integration.spm.test_man_spm/SPMManTest/test_man_spm/

**Comment by gtmanfred** [comment]
Fixed by https://github.com/saltstack/salt/pull/45570
