### ISSUE TITLE
[2017.7] Proxy Minion Tests for Py3 are failing

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#678]
Possibly the same issue as #564 but for 2017.7 instead of oxygen? I didn't investigate too closely, so I'm not sure. That was fixed with this: https://github.com/saltstack/salt/pull/44973

Looks like the proxy minion test process is having a hard time starting: https://jenkins.saltstack.com/job/2017.7/view/Proxy/

**Comment by gtmanfred** [comment]
+1 this is the fix.

**Comment by rallytime** [comment]
Hooray!

**Comment by gtmanfred** [comment]
![party](https://media.giphy.com/media/hsBZfDG7wiWHu/giphy.gif)
