### ISSUE TITLE
[2017.7] PY3: Transport tests are not getting through git.salt run

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#679]
The Python 3 Transport tests on 2017.7 are not able to get past the salt-jenkins states. They both have the following error:

```
18:11:58 [CRITICAL] Rendering SLS 'base:git.salt' failed: Jinja variable 'transport_reqs' is undefined
18:11:58 local:
18:11:58     Data failed to compile:
18:11:58 ----------
18:11:58     Rendering SLS 'base:git.salt' failed: Jinja variable 'transport_reqs' is undefined
18:11:59 --------------------------------------------------------------------------------
18:11:59  * Failed execute command. Exit code: 1
```

https://jenkins.saltstack.com/job/2017.7/view/Transport/

@dubb-b Can you look into this please? We need to see test results here in case some things failing in the test run as we get ready for 2017.7.3. :)

**Comment by dubb-b** [comment]
@rallytime These are all running now. The issue was the gitfs needed to be updated with @Ch3LL changes. I did that kicked them off and made sure they made it to the test stage. The ubuntu14 one ran out of memory. I upped the instance size and it looked better.
