### ISSUE TITLE
[oxygen/PRs/develop] Test daemons not starting

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#683]
The test deamons are not starting on the oxygen and develop branches. They're also not running on PRs either. I am not sure if this is related to the AWS images, some updated package via salt-jenkins, or salt code. Though since this popped up on multiple branches all at once, without a merge forward, I don't think it's a change in salt-code.

@gtmanfred Can you look into this? You and @dubb-b have the most experience with the new set-up in AWS and I am not sure what the reason is offhand.

**Comment by dubb-b** [comment]
@rallytime some of these are due to the EPEL repo being unavailable yesterday. I started a few of them and will be looking at what happens. @gtmanfred if you find anything else let me know.

**Comment by rallytime** [comment]
@dubb-b OK good to know. 👍

I am seeing this across multiple distros. For example, the Ubuntu PR tests are also having this problem, which shouldn't be related to the EPEL issues.

**Comment by dubb-b** [comment]
Also, to update everyone to keep in sync, this doesnt seem to be AWS related, I just created a debian9 off of develop, it had the same issue. It is in Linode.
Here is the job: https://jenkins.saltstack.com/job/develop/job/salt-develop-linode-debian9/106/console

**Comment by gtmanfred** [comment]
I am spinning up a local instance to see if I can replicate it and see what is happening.

**Comment by gtmanfred** [comment]
and it fixed itself

**Comment by rallytime** [comment]
This is happening again this morning. Re-opening.
