### ISSUE TITLE
[2017.7] Arch not getting past git.salt state run

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#687]
Both Py2 and Py3 runs are affected. Here's the error:
```
15:28:32 local:
15:28:32     Data failed to compile:
15:28:32 ----------
15:28:32     Rendering SLS 'base:gcc' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'pkg.list_repo_pkgs'
```

@dubb-b Can you look into this, please?

**Comment by Ch3LL** [comment]
I believe this is related to the salt version. We might need to upgrade the salt version on arch because that function was added later on.

**Comment by dubb-b** [comment]
Will update now, thanks @Ch3LL

**Comment by dubb-b** [comment]
Those have been updated and are running tests now.

@rallytime can you validate and close?

**Comment by rallytime** [comment]
Yep, fixed! Thank you. 👍
