### ISSUE TITLE
[2016.11.9] CentOS 7 Proxy tests not getting past git.salt run

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#706]
I have seen this in the salt-jenkins travis/kitchen salt tests, too, but basically the `git.salt` state runs, and complete successfully. But then Jenkins thinks that it didn't for some reason, and aborts:
```
11:42:40 Summary for local
11:42:40 -------------
11:42:41 Succeeded: 66 (changed=47)
11:42:41 Failed:     0
11:42:41 -------------
11:42:41 Total states run:     66
11:42:42  * Failed execute command. Exit code: 255
11:42:42 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
11:42:42  * The execution of the 'git.salt' SLS failed
11:42:42 Build step 'Execute shell' marked build as failure
```
I was thinking it just had something to do with kitchen salt, but now I am seeing it here: https://jenkins.saltstack.com/job/2016.11.9/view/Proxy/job/2016.11/

I'm not sure if this is a configuration issue or something else. @gtmanfred can you look into that? I don't think this should block the 2016.11.9 release since we have proxy test results from the other build and they're OK, but it might be something we should keep an eye on and fix.

**Comment by rallytime** [comment]
It's happening on the 2016.11 branch PY2 tests too: https://jenkins.saltstack.com/job/2016.9/job/salt-2016_9-linode-cent7/lastFailedBuild/console

**Comment by gtmanfred** [comment]
#717
