### ISSUE TITLE
[2017.7.3] CentOS 6 not bootstrapping

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#711]
```
Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -p 22 root@173.255.212.172 '/tmp/.saltcloud-b1b78656-d526-49a7-98da-4c4e013fb8c9/deploy.sh -c '"'"'/tmp/.saltcloud-b1b78656-d526-49a7-98da-4c4e013fb8c9'"'"' -P -y -x python2.7 git v2016.11.3'' failed. Exit code: 1
12:32:56 --------------------------------------------------------------------------------
12:32:56  * Failed execute command. Exit code: 1
12:32:56 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
12:32:56 
 * Failed to bootstrap the cloud minion
```

https://jenkins.saltstack.com/job/2017.7.3/job/salt-linode-cent6/lastFailedBuild/console

**Comment by gtmanfred** [comment]
@dubb-b can you run a `salt-cloud -u` on all these boxes to update the bootstrap script?

Thanks,
Daniel

**Comment by dubb-b** [comment]
@gtmanfred The command was ran against the new slaves only. Let me know if you need it ran on the others.

**Comment by gtmanfred** [comment]
i believe the other ones already have a new enough salt-bootstrap script, so we should be good.

**Comment by gtmanfred** [comment]
https://jenkins.saltstack.com/job/2017.7.3/job/salt-linode-cent6/4/console
got past bootstrap
