### ISSUE TITLE
[2017.7.3] CentOS 7 Proxy tests not bootstrapping

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#713]
https://jenkins.saltstack.com/job/2017.7.3/view/Transport/job/salt-2017_7-linode-tcp-cent7/lastFailedBuild/console

**Comment by gtmanfred** [comment]
These are tcp transport tests.

Is it just all centos 7 git.salt bootstrapping is failing?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
#717
