### ISSUE TITLE
[2016.11/2017.7/Oxygen] Centos 7 is segfaulting on bootstrap

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt-jenkins#717]
https://jenkinsci.saltstack.com/job/2017.7/job/salt-centos-7-py2/lastBuild/console

It looks like it is the same segfault on the weakrefs that we were seeing with opensuse.

https://bugzilla.suse.com/show_bug.cgi?id=1073748
https://bugs.python.org/issue29347

**Comment by gtmanfred** [comment]
Reported to redhat and centos

https://bugs.centos.org/view.php?id=14381
https://bugzilla.redhat.com/show_bug.cgi?id=1535190

**Comment by rallytime** [comment]
This is fixed now.
