### ISSUE TITLE
Ubuntu 17.04 is EOL: Upgrade to Ubuntu 17.10

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#719]
We need to remove the 17.04 tests, and create some 17.10 tests.

However, this is blocked on https://github.com/saltstack/salt-bootstrap/issues/1193

**Comment by rallytime** [comment]
I just checked this and the current stable bootstrap works fine on 17.10. I don't think fixing the bootsrap script should block this, at least for now.

**Comment by rallytime** [comment]
@dubb-b There are a couple of issues. Checked means it's fixed. No check means there's something wrong.

- [ ] 2016.11 (started - need to check result)
- [x] 2016.11.9
- [ ] 2017.7 PY2 (waiting for build slot - need to check result)
- [ ] 2017.7 PY3 - not bootstrapping
- [x] 2017.7.3 PY2
- [x] 2017.7.3 PY3
- [x] oxygen PY2 - not getting past the git.salt state. see #792
- [x] oxygen PY3
- [ ] develop PY2 - not bootstrapping
- [ ] develop PY3 - not bootstrapping

**Comment by dubb-b** [comment]
@rallytime These should all be working now. If you could just double check me that would be swell.

**Comment by rallytime** [comment]
Looks great! Thanks @dubb-b
