### ISSUE TITLE
Mac 10.11 py2 boto tests failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#721]
The following tests are failing on 10.11 py2 boto tests:

  unittest.loader.ModuleImportFailure.unit.modules.boto_vpc_test
  unittest.loader.ModuleImportFailure.unit.states.boto_vpc_test

http://mac-jenkins:8080/job/2016.11/job/2016.11.9/job/macOS-10.11/lastFailedBuild/

**Comment by rallytime** [comment]
This was fixed on linux with https://github.com/saltstack/salt-jenkins/pull/697

**Comment by Ch3LL** [comment]
k the tests where run recently so will check to see if the git repo is updating correctly.

**Comment by rallytime** [comment]
Ah, actually these are failing on linux as well. It's fixed here: https://github.com/saltstack/salt/pull/45435

But that didn't make it into the new branch. I don't think these failures should block the release.

**Comment by Ch3LL** [comment]
k i'll remove the release label but wait to close when re-running the tests.
