### ISSUE TITLE
[2017.7] Mac 10.12 py2 pkg tests failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#724]
integration.modules.test_pkg.PkgModuleTest.test_pkg_upgrade_has_pending_upgrades
integration.modules.test_pkg.PkgModuleTest.test_version_cmp

http://mac-jenkins:8080/job/2017.7/job/macOS-10.12/317/#showFailuresLink

**Comment by garethgreenaway** [comment]
@Ch3LL I don't see the test_version_cmp test in the list of failures.
