### ISSUE TITLE
[2017.7] Mac 10.12 py2 boto test failures

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#727]
unittest.loader.ModuleImportFailure.test_boto_elb
unittest.loader.ModuleImportFailure.test_boto_secgroup
unittest.loader.ModuleImportFailure.test_boto_vpc
unittest.loader.ModuleImportFailure.test_boto_vpc
unittest.loader.ModuleImportFailure.test_boto

http://mac-jenkins:8080/job/2017.7/job/macOS-10.12/317/#showFailuresLink

**Comment by rallytime** [comment]
These are failing on linux too. This should fix them https://github.com/saltstack/salt/pull/45465

**Comment by rallytime** [comment]
I wouldn't worry about this blocking the release. It's a test-suite issue.

**Comment by Ch3LL** [comment]
This is no longer failing: http://mac-jenkins:8080/job/2017.7/job/2017.7.3/job/macOS-10.12/7/ closing
