### ISSUE TITLE
opensuse 13 and bower on 2015.2 branch

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt-jenkins#73]
Hi If you want to test bower on opensuse 13,
you should add the following repo:
http://download.opensuse.org/repositories/devel:/languages:/nodejs/openSUSE_13.1/

otherwise it won't build and work.
https://jenkins.saltstack.com/job/salt-linode-opensuse13/1026/console

**Comment by aboe76** [comment]
@s0undt3ch ping :)

**Comment by s0undt3ch** [comment]
Sorry it took me this long to reply to you ping @aboe76. 233cef32de0ffd0008edc85c96c190fcb8e459ee should take care of this.
