### ISSUE TITLE
[2017.7] Mac 10.11 py3 test virt test failrues

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#746]
integration.modules.test_virt.VirtTest.test_default_esxi_profile
integration.modules.test_virt.VirtTest.test_default_kvm_profile

http://mac-jenkins:8080/job/2017.7/job/macOS-py3-10.11/32/#showFailuresLink

**Comment by frogunder** [comment]
I cant replicate this. Will need to re-run tests and check results.
