### ISSUE TITLE
[2017.7] Mac 10.11 py3 archive test failures

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#748]
unit.states.test_archive.ArchiveTestCase.test_extracted_tar
unit.states.test_archive.ArchiveTestCase.test_tar_bsdtar
unit.states.test_archive.ArchiveTestCase.test_tar_gnutar

http://mac-jenkins:8080/job/2017.7/job/macOS-py3-10.11/32/#showFailuresLink

ping @frogunder i think you fixed these. I am thinking maybe your fix might just need to be backported to this branch?

**Comment by frogunder** [comment]
Just double checked this, and it is working with the fix done for oxygen branch.
So it seems this PR just needs to be backported: https://github.com/saltstack/salt/pull/45332

**Comment by frogunder** [comment]
From what I see we have to use on 2017.7 branch `salt.utils.is_darwin()`, while on oxygen branch it is `salt.utils.platform.is_darwin()`. `platform` was added so to backport it would maybe not work correctly.
