### ISSUE TITLE
[2017.7.3] Investigate Transport Test Failures

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#749]
The transport tests don't have any results on the 2017.7.3 branch. This needs to be investigated and fixed. Since the CentOS 7 tests are having other general issues, it's best to focus on the Ubuntu tests first.

@gtmanfred Can you please look into this?

https://jenkins.saltstack.com/job/2017.7.3/view/Transport/

This looks to also be happening on the 2017.7 branch as well.

**Comment by gtmanfred** [comment]
these pass when run individually.

Closing
