### ISSUE TITLE
[oxygen] Ubuntu 16 (and some others) failing 4 ini_manage unit tests

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#789]
- unit.modules.test_ini_manage.IniManageTestCase.test_empty_lines_preserved_after_edit
- unit.modules.test_ini_manage.IniManageTestCase.test_empty_lines_preserved_after_multiple_edits
- unit.modules.test_ini_manage.IniManageTestCase.test_empty_value_preserved_after_edit
- unit.modules.test_ini_manage.IniManageTestCase.test_set_option

https://jenkins.saltstack.com/job/Oxygen/job/oxygen-salt-ubuntu16.04-py2/lastCompletedBuild/testReport/

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/45658

**Comment by rallytime** [comment]
Fixed.
