### ISSUE TITLE
[oxygen] 3 gitfs fileserver unit tests failing (Ubuntu 16 and others)

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#790]
- unit.fileserver.test_gitfs.GitFSTest.test_dir_list
- unit.fileserver.test_gitfs.GitFSTest.test_envs
- unit.fileserver.test_gitfs.GitFSTest.test_file_list

https://jenkins.saltstack.com/job/Oxygen/job/oxygen-salt-ubuntu16.04-py2/lastCompletedBuild/testReport/

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/45658

**Comment by rallytime** [comment]
Fixed.
