### ISSUE TITLE
[oxygen] 1 inspect_fsdb unit test failure on Ubuntu 16 (and some others)

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#791]
- unit.modules.test_inspect_fsdb.InspectorFSDBTestCase.test_create_table

https://jenkins.saltstack.com/job/Oxygen/job/oxygen-salt-ubuntu16.04-py2/lastCompletedBuild/testReport/

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/45658

**Comment by rallytime** [comment]
Fixed
