### ISSUE TITLE
[2017.7.3] Some PKG tests failing on Arch/Fedora 27

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#793]
Arch: https://jenkins.saltstack.com/job/2017.7.3/job/salt-linode-arch/lastCompletedBuild/testReport/
Fedora 27: https://jenkins.saltstack.com/job/2017.7.3/job/2017.7-salt-fedora27-py2/lastCompletedBuild/testReport/

These pkg tests started tipping over yesterday. This is likely because of the change made against 2017.7.3 here: https://github.com/saltstack/salt/pull/45636

**Comment by terminalmage** [comment]
Should be fixed via https://github.com/saltstack/salt/pull/45666.
