### ISSUE TITLE
[oxygen] Debian 9 PY3 not bootstrapping

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#795]
https://jenkins.saltstack.com/job/Oxygen/view/Branch%20Python%203/job/oxygen-salt-debian9-py3/lastFailedBuild/console

**Comment by dubb-b** [comment]
@rallytime Here is that one. I will validate the rest in the morning.
https://jenkins.saltstack.com/job/Oxygen/view/Branch%20Python%203/job/oxygen-salt-debian9-py3/80/consoleFull

**Comment by rallytime** [comment]
That was the only one with problems that I saw. Looks like it's happy now. Thanks!
