### ISSUE TITLE
[oxygen] Arch is failing 2 GroupAdd integration tests

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#804]
The following 2 tests are failing on Arch (both on PY2 and PY3):
- integration.modules.test_groupadd.GroupModuleTest.test_add_system_group
- integration.modules.test_groupadd.GroupModuleTest.test_add_system_group_gid

https://jenkins.saltstack.com/job/Oxygen/job/oxygen-salt-arch-py2/lastFailedBuild/

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/45731
