### ISSUE TITLE
[oxygen] CentOS 6 and 7 Failing many integration ssh tests

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#805]
https://jenkins.saltstack.com/job/Oxygen/job/oxygen-salt-cent7-py2/lastCompletedBuild/testReport/

I see these on Py2, but I haven't looked at the results for Py3. Here's the list:

- integration.ssh.test_grains.SSHGrainsTest.test_grains_items
- integration.ssh.test_raw.SSHRawTest.test_ssh_raw
- integration.ssh.test_pillar.SSHPillarTest.test_pillar_get
- integration.ssh.test_pillar.SSHPillarTest.test_pillar_get_doesnotexist
- integration.ssh.test_pillar.SSHPillarTest.test_pillar_items
- integration.ssh.test_state.SSHStateTest.test_show_highstate
- integration.ssh.test_state.SSHStateTest.test_show_lowstate
- integration.ssh.test_state.SSHStateTest.test_state_running
- integration.ssh.test_state.SSHStateTest.test_state_show_top
- integration.ssh.test_state.SSHStateTest.test_state_apply
- integration.ssh.test_state.SSHStateTest.test_state_high
- integration.ssh.test_state.SSHStateTest.test_state_low
- integration.ssh.test_state.SSHStateTest.test_state_request_check_clear
- integration.ssh.test_state.SSHStateTest.test_state_run_request
- integration.ssh.test_state.SSHStateTest.test_state_show_sls
- integration.ssh.test_state.SSHStateTest.test_state_single
- integration.ssh.test_state.SSHStateTest.test_state_sls_id
- integration.ssh.test_mine.SSHMineTest.test_ssh_mine_get

**Comment by terminalmage** [comment]
This is caused by the same issue as https://github.com/saltstack/salt-jenkins/issues/806 and should be fixed by https://github.com/saltstack/salt/pull/45725.

**Comment by rallytime** [comment]
@terminalmage These are fixed for CentOS 7, but still seem to be failing on CentOS 6, even though they have the fixed mentioned above. Perhaps something else is going wrong there.

**Comment by rallytime** [comment]
https://jenkins.saltstack.com/job/Oxygen/job/oxygen-salt-cent6-py2/lastFailedBuild/

**Comment by DmitryKuzmenko** [comment]
Reproduced some in Docker. Investigating.

**Comment by DmitryKuzmenko** [comment]
I'm stuck here. Probably #46477 will fix it, let's see.
Also I've asked Brett to help me to get one of that Jenkins test machines running after the test pass so I can log in and re-run some tests with more trace logging. Waiting for that machine.

**Comment by rallytime** [comment]
This is fixed now. 🎉
