### ISSUE TITLE
[oxygen] tls unit tests failing on Python 3

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#809]
unit.modules.test_tls.TLSAddTestCase.test_create_ca
unit.modules.test_tls.TLSAddTestCase.test_create_ca_signed_cert
unit.modules.test_tls.TLSAddTestCase.test_create_csr
unit.modules.test_tls.TLSAddTestCase.test_create_pkcs12
unit.modules.test_tls.TLSAddTestCase.test_create_self_signed_cert
unit.modules.test_tls.TLSAddTestCase.test_pyOpenSSL_version_destructive
unit.modules.test_tls.TLSAddTestCase.test_recreate_ca
unit.modules.test_tls.TLSAddTestCase.test_recreate_ca_signed_cert
unit.modules.test_tls.TLSAddTestCase.test_recreate_csr
unit.modules.test_tls.TLSAddTestCase.test_recreate_pkcs12
unit.modules.test_tls.TLSAddTestCase.test_recreate_self_signe

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/45729 along with two other failures.
