### ISSUE TITLE
[oxygen] Transport tests are not getting any test results back

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#810]
https://jenkins.saltstack.com/job/Oxygen/view/Transport/

**Comment by gtmanfred** [comment]
Looks like the job results are getting picked up, but are not being showed in the /Transport folder.

@dubb-b can you take a look at those patterns to figure out why it might not be seeing the job dirs?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
FIxed the Failed Tests column to show the test results.

Closing
