### ISSUE TITLE
[oxygen] Several modjk unit tests are failing

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#812]
unit.states.test_modjk.ModjkTestCase.test_worker_activated
unit.states.test_modjk.ModjkTestCase.test_worker_disabled
unit.states.test_modjk.ModjkTestCase.test_worker_recover
unit.states.test_modjk.ModjkTestCase.test_worker_stopped

These popped up on all builds, but here's a link to Debian 9 where they're the only ones failing: https://jenkins.saltstack.com/job/Oxygen/job/oxygen-salt-debian9-py2/lastCompletedBuild/testReport/

**Comment by gtmanfred** [comment]
fixed in #45770
