### ISSUE TITLE
[oxygen.rc1] Create Mac Builds for new RC 1 branch

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#816]

**Comment by dubb-b** [comment]
@rallytime These are created. The build queue is 12 deep. I will check on them later this eve.

**Comment by dubb-b** [comment]
@rallytime all of these are created and running. Although the machine is hitting some thresholds with resources. We have to set the node to only one Jenkins executor, so the runs are taking days to complete. So this one may take some time to resolve. Once we get the new hardware, we should be in a better state I hope.

**Comment by dubb-b** [comment]
@rallytime This is pretty backed up, other than a couple, they were all passing.
