### ISSUE TITLE
[oxygen.rc1] OpenSUSE on PY3 tests isn't bootstrapping

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#818]
https://jenkins.saltstack.com/job/oxygen.rc1/view/Branch%20Python%203/job/oxygen-salt-opensuse42-py3/

**Comment by dubb-b** [comment]
@rallytime this is complete for the Python 3 ones.
https://jenkins.saltstack.com/job/oxygen.rc1/view/Branch%20Python%203/job/oxygen-salt-opensuse42-py3/10/console
