### ISSUE TITLE
[oxygen.rc1] CentOS 7 PY 3 tests not displaying test reports

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#821]
The tests run, and it generates the reports, but each build is greyed out because it doesn't have the test report.

Appears to be something to do with the workspace.
```
06:57:37 [xUnit] [INFO] - Starting to record.
06:57:37 [xUnit] [INFO] - Processing JUnit
06:57:37 [xUnit] [INFO] - [JUnit] - 200 test report file(s) were found with the pattern 'artifacts/unittests/*.xml' relative to '/var/jenkins/workspace/oxygen.rc1/oxygen-salt-cent7-py3' for the testing framework 'JUnit'.
06:57:38 [xUnit] [INFO] - Check 'Failed Tests' threshold.
06:57:38 [xUnit] [INFO] - Check 'Skipped Tests' threshold.
06:57:38 [xUnit] [INFO] - Setting the build status to ABORTED
```
https://jenkins.saltstack.com/job/oxygen.rc1/view/Branch%20Python%203/job/oxygen-salt-cent7-py3/
@dubb-b I think this is in your realm. Can you take a look?

**Comment by dubb-b** [comment]
@rallytime this is happening due to the build timeout plugin. It was set to 120 minutes and that threshold was being hit. I set to 600 to see how long it will really take. It may be that we need to look at the tests on that. I thought it may have been memory/CPU so increased the size. That didn't help. So we should see if it still times out after 600 mins.

**Comment by rallytime** [comment]
Ah OK - i just read that message I posted again and i clearly misread that originally. `test report files were found`...derp.

**Comment by dubb-b** [comment]
@rallytime https://jenkins.saltstack.com/job/oxygen.rc1/view/Branch%20Python%203/job/oxygen-salt-cent7-py3/6/console

Its failing now. But its passing `git.salt`
Let me know if you need anything more on this.

**Comment by rallytime** [comment]
Nope, looks good. Thanks!
