### ISSUE TITLE
[develop] Many zfs module unit tests failing

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#824]
These started breaking because of the unicode changes. The module/test needs to be fixed to handle the unicode changes appropriately:

https://jenkins.saltstack.com/job/develop/job/salt-dev-linode-ubuntu16/2124/#showFailuresLink

**Comment by sjorge** [comment]
I hit the same issue while reworking bits for PR #45855 (that one still has other unicode issues, but they should eventually go into Florine so enough time to fix those before the merge.

So the fix of removing the PY2 handling looks good to me.

**Comment by rallytime** [comment]
👋 @sjorge! I think that PR from me caused a merge-conflict in your PR actually, now that i think about it. Sorry about that. :)

I'll close this because those tests are happy now.

**Comment by sjorge** [comment]
@rallytime don't worry about, I had to rebase a few times already due to merge conflicts.
