### ISSUE TITLE
[develop] Doc test build is failing

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#825]
https://jenkins.saltstack.com/job/develop/view/Docs/job/Develop/lastFailedBuild/

**Comment by rallytime** [comment]
I'm tossing this your way @terminalmage - this is only on develop, so release blockers should come first. I gave the rest of the develop test failures currently filed to Dmitry earlier today.

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/46112
