### ISSUE TITLE
2 gitfs fileserver unit tests failing on Arch + Fedora 27

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#844]
https://jenkins.saltstack.com/job/oxygen.rc1/job/oxygen-salt-arch-py2/lastCompletedBuild/testReport/

- unit.fileserver.test_gitfs.Pygit2Test.test_envs
- unit.fileserver.test_gitfs.Pygit2Test.test_ref_types_per_remote

These are failing on oxygen.rc1 and oxygen branches.

These are failing in both the Arch and Fedora 27 builds.

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/46080
