### ISSUE TITLE
[oxygen.rc1] Arch image isn't working

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#848]
Looks like something has changed in AWS. @dubb-b Can you take a look?

https://jenkins.saltstack.com/job/oxygen.rc1/job/oxygen-salt-arch-py2/lastFailedBuild/

```
16:45:42 [INFO    ] salt-cloud starting
16:45:45 [INFO    ] Creating Cloud VM Zjk-oxygen_rc1-oxygen-arch-py2-29 in us-east-1
16:45:45 [INFO    ] Attempting to look up root device name for image id ami-e80d6792 on VM Zjk-oxygen_rc1-oxygen-arch-py2-29
16:45:45 
Error: There was a profile error: There was an error querying EC2 for the root device of image id ami-e80d6792. Empty response.
16:45:46 --------------------------------------------------------------------------------
16:45:46  * Failed execute command. Exit code: 1
16:45:46 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
16:45:46 
 * Failed to bootstrap the cloud minion
16:45:46 Build step 'Execute shell' marked build as failure
```
This is failing for the PY2 and PY3 jobs.

**Comment by dubb-b** [comment]
@rallytime https://jenkins.saltstack.com/job/oxygen.rc1/job/oxygen-salt-arch-py2/30/console

These are updated now with the new AMI.

**Comment by rallytime** [comment]
This is failing again on the 2018.3 node: https://jenkins.saltstack.com/job/2018.3/job/oxygen-salt-arch-py2/lastFailedBuild/

**Comment by rallytime** [comment]
@dubb-b To clarify, this is failing on both 2018.3.0rc1 and 2018.3.
