### ISSUE TITLE
Appveyor build for salt-jenkins

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt-jenkins#855]
We have seen some flakiness when salt-jenkins installs in Windows environments. Add an Appveyor build that installs salt-jenkins. This build will run on pull requests to the salt-jenkins repository in hopes of catching changes that might break Windows builds

**Comment by dwoz** [comment]
This is taking longer than I expected. I'm working through dusting off kitchen-salt to work with windows. As of right now, I am able to get salt-jenkins installed via kitchen-salt on both vagrant boxes and in Appveyor. The tests are not running in either of these environments yet however. I'm reaching out to a few people today to try and close the gaps in my understanding of all this.

**Comment by rallytime** [comment]
Sounds good. Thanks @dwoz

**Comment by dwoz** [comment]
Finally created a PR for this one. I'll likely need to make some minor change after @gtmanfred reviews.

**Comment by dwoz** [comment]
We've merged #868 because it was holding up some other work. I still have some issues to work through for python 3 and vagrant builds in salt-jenkins

**Comment by dwoz** [comment]
We've added python 3 builds in #874. I'm closing this issue since Appveyor builds seem good now.
