### ISSUE TITLE
Update bootstrap script on branch nodes to latest develop

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#877]
The bootstrap script needs to be updated in `/etc/salt/cloud.deploy.d/` on the branch nodes to the latest version of develop: https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh

This is necessary because it contains a fix for the Cent6 test runs. They are currently failing because bootstrap installs `tornado 5.0`. The bootstrap develop version contains a fix where tornado is pinned at `<5.0` for bootstrap installations passing the `-P` flag.

- [x] 2017.7 (new jenkins only?)
- [x] 2018.3
- [x] 2018.3.0rc1
- [x] develop

The new jenkins probably needs this update, too.

**Comment by dubb-b** [comment]
@rallytime I updated this. I am going to kick off some builds and make sure it all works.
