### ISSUE TITLE
[develop] LDAP Auth Unit test failing on Develop branch

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#881]
- unit.auth.test_ldap.LDAPAuthTestCase.test_groups_freeipa

```
Traceback (most recent call last):
  File "/testing/tests/unit/auth/test_ldap.py", line 71, in test_groups_freeipa
    self.assertIn('saltusers', salt.auth.ldap.groups('saltuser', password='password'))
  File "/testing/salt/auth/ldap.py", line 364, in groups
    for user in result[_config('accountattributename'), _config('groupattribute')]:
KeyError: ('memberUid', 'memberOf')
```

This has been failing for a while on the develop branch, I just hadn't had time to file an issue for it. It's failing consistently on multiple builds (PRs and the branch)

@DmitryKuzmenko can you look into this?

**Comment by DmitryKuzmenko** [comment]
I've reverted https://github.com/saltstack/salt/pull/45859 for now. It will fix the test. Anyway the reverted changes need to be updated because they partially lost after unicode fixes.
I've opened a discussion with the author.
