### ISSUE TITLE
Bower install broken on some PY2 runs (affects PRs)

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#907]
I am seeing this fail on Ubuntu 14.04 for Python 2 builds on PRs and branches. 

Note that it isn't failing everywhere, however. It's failing on the following distros:
- [ ] Ubuntu 14.04 PY2: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/21301/consoleFull
- [ ] Centos 6: https://jenkins.saltstack.com/job/2018.3/job/oxygen-salt-cent6-py2/lastFailedBuild/console

This is passing just fine on most other builds, it's just affecting PRs that I noticed it so quickly. For example, Ubuntu 16.04 is fine, and so is CentOS7.

CentOS7 PY2 builds are also failing but for a different reason. I will file another issue for that.

**Comment by gtmanfred** [comment]
Fixed by #909 
A cherry-pick has also been merged into 2018.3 and master.
