### ISSUE TITLE
[2017.7] [debian 8] [py3] integration.states.test_compiler.CompileTest.test_jinja_deep_error

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt-jenkins#916]
```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_compiler.py", line 34, in test_jinja_deep_error
    ret[0].strip().endswith('Exception: hehehe'))
AssertionError: False is not true
```

**Comment by rallytime** [comment]
@terminalmage Can you look into this one?

https://jenkinsci.saltstack.com/job/2017.7/view/Python3/job/salt-debian-8-py3/lastCompletedBuild/testReport/

**Comment by terminalmage** [comment]
@gtmanfred I can't reproduce on Debian 8 using Python 3 or Python 2 at the head of 2017.7. Is this still failing for you?

**Comment by gtmanfred** [comment]
Looks like it has gone away on 2017.7 in jenkinsci

**Comment by rallytime** [comment]
@gtmanfred and @terminalmage This has popped up again.

**Comment by dwoz** [comment]
@rallytime  @terminalmage @gtmanfred 

I can confirm I've seen this pop up intermittently.

**Comment by rallytime** [comment]
Replaced with #1053
