### ISSUE TITLE
[2018.3] Lint build doesn't have "violations" link

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#922]
There is a lint build that failed on the 2018.3 branch recently and when I went to see what the issue was, I noticed there is not a "Violations" link in the left-hand side bar in JenkinsCI like there is in the old Jenkins.

I did not check the other branches, but they should have this too. @gtmanfred Can you fix this and check the other branches for the lint builds?

- [x] 2017.7
- [x] 2018.3
- [x] develop

I am not sure what, if anything, needs to be adjusted in branch set up automation for this.

Here's an example for reference: https://jenkinsci.saltstack.com/job/2018.3/job/salt-2018.3-lint/8/

**Comment by gtmanfred** [comment]
I added a Report Violations block to the configuration, and had it pull `pylint-report*.xml`

I am going to assign this to brett to get it added to the job template.

Daniel

**Comment by dubb-b** [comment]
Thanks @gtmanfred will get it done.

**Comment by rallytime** [comment]
Nice nice nice

**Comment by dubb-b** [comment]
@gtmanfred this is complete.
