### ISSUE TITLE
[develop] unit.test_pillar.PillarTestCase.test_includes_override_sls failure

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#930]
The following test is failing on the develop branch:

- unit.test_pillar.PillarTestCase.test_includes_override_sls

This test is failing on both PY2 and PY3. Here's a link to the latest Cent7 PY 2 run: https://jenkins.saltstack.com/job/develop/job/salt-linode-cent7/lastCompletedBuild/testReport/

This test is new and started failing during a merge forward into the develop branch. It passes just fine on the 2018.3 branch.

@terminalmage You wrote the test originally, so I am going to assign this to you to make sure a bug has not snuck into the develop branch.

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/47161
