### ISSUE TITLE
mac tests can't bootstrap when using 2017.7.* bootstrap version

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#976]
When attempting to force the mac tests to bootstrap 2017.7.* versions it will not bootstrap because salt-testing has a couple of issues.

1. it hard codes the pkg name and in >= 2017.7 release we have renamed the pkg to include either py2 or py3. 
2. it is not accurately comparing the md5 hash. 

ping @dubb-b since you manage the salt-testing instances can you or someone from the team take a look at this?

**Comment by dubb-b** [comment]
@Ch3LL this issue should be fixed.
