### ISSUE TITLE
VMWare Cloud tests failing

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#979]
The VMWare cloud tests are failing on the new jenkins set up. They are failing on all branches.

I bet this has to do with the office move since these hosts were at the old office. Perhaps something went awry during the move.

@dubb-b Can you look into this?

**Comment by gtmanfred** [comment]
If you are looking at the new jenkins, this is failing because the test instances are in aws, and the vmware instance is in our datacenter and it can't talk to them, we could attach our datacenter network to the vpc in aws to make those pass.

**Comment by rallytime** [comment]
Yeah, I was looking at the new Jenkins.

**Comment by rallytime** [comment]
This is fixed now. 👍
