### ISSUE TITLE
EC2 Cloud Tests failing for Windows

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#980]
There are 2 tests failing with the new cloud tests for spinning up windows VMs:

- integration.cloud.providers.test_ec2.EC2Test.test_win2012r2_winrm
- integration.cloud.providers.test_ec2.EC2Test.test_win2016_winrm

These are failing on both the Py2 and Py3 builds for all active branches.

https://jenkinsci.saltstack.com/job/2017.7/view/Cloud/job/salt-centos-7-py2-cloud/4/

@dwoz Can you take a look into these?

**Comment by dwoz** [comment]
Found this error in the failing test logs.
```
{'Errors': {'Error': {'Message': 'The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.', 'Code': 'VPCResourceNotSpecified'}}, 'RequestID': '10a2117e-f4b6-47e5-97a2-dfae5f2d22de'}
```

**Comment by rallytime** [comment]
Ah, so just need to change the instance id we're using for the tests it sounds like?

**Comment by rallytime** [comment]
This is fixed.
