### ISSUE TITLE
[2018.3][Fedora 28] integration.ssh.test_master.SSHMasterTestCase.test_service

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt-jenkins#999]
https://jenkinsci.saltstack.com/job/2018.3.1/job/salt-fedora-28-py2/20/testReport/integration.ssh.test_master/SSHMasterTestCase/test_service/

**Comment by rallytime** [comment]
@terminalmage Can you take a look at this?

**Comment by gtmanfred** [comment]
I am looking at this one already

**Comment by rallytime** [comment]
@gtmanfred Oh, OK. Thanks!

**Comment by gtmanfred** [comment]
This was fixed by #997
